ThePalaceProject/android-core

.ci-local/credentials-fake.sh
.ci-local/credentials.sh
README.md
build.gradle
build_apk.gradle
simplified-app-openebooks/gradle.properties
simplified-app-palace/gradle.properties
simplified-app-simplye/gradle.properties
simplified-app-vanilla/build.gradle

Rename gradle properties to `org.thepalaceproject.*`.
This makes life easier for developers who want to build both the NYPL-Simplified and ThePalaceProject forks, since gradle properties can now be set differently.
Rename the properties in your gradle.properties file. Local builds should continue to work.
https://github.com/ThePalaceProject/mobile-certificates/pull/1 should be merged first.
The README is updated.
@ray-lee ran a local build.

Rename gradle properties.

---

.ci-local/credentials.sh
simplified-app-palace/build.gradle
simplified-app-palace/src/main/res/values/features.xml

Use the new Adobe cert for Palace.
The new cert has the correct app id and app name for Palace, instead of RayBooks.
Borrowing and reading Adobe-protected books should continue to work.
n/a
n/a
@ray-lee ran the Palace app.

Incorporate new Adobe cert for Palace.

---

simplified-documents/src/main/java/org/librarysimplified/documents/internal/SimpleDocument.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentListenerDelegate.kt
simplified-ui-accounts/src/main/java/org/nypl/simplified/ui/accounts/AccountDetailEvent.kt
simplified-ui-accounts/src/main/java/org/nypl/simplified/ui/accounts/AccountDetailFragment.kt
simplified-ui-accounts/src/main/java/org/nypl/simplified/ui/accounts/AccountDetailViewModel.kt
simplified-ui-accounts/src/main/res/layout/account.xml
simplified-ui-accounts/src/main/res/values/strings.xml

Allow users to view library documents from account screen 
https://www.notion.so/lyrasis/Allow-users-to-view-library-documents-from-account-screen-779d77a7d24d4794a42b833101cb308e
Try to add a new library (New York Public library) and check if you can open EULA, Privacy Policy and Content Licenses docs
n/a
n/a
@talesgurjao ran the Palace app.

Enable account-specificc documentation viewer

---

simplified-ui-accounts/src/main/res/values/strings.xml
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFeedArguments.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFeedFragment.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFeedViewModel.kt
simplified-ui-navigation-tabs/src/main/java/org/nypl/simplified/ui/navigation/tabs/BottomNavigators.kt

Enables the library name/switch action in the action bar
https://www.notion.so/lyrasis/Show-current-library-on-Books-and-Holds-31ab7396246d44df9e2af3a9adf8b560
Open the books/hold tabs and observe the library name and action icon (need to set showBooksFromAllAccounts to false)
n/a
n/a
@talesgurjao ran the Palace app.

Display current library in the action bar

---

simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/BorrowContextType.kt
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/BorrowRequest.kt
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/BorrowTask.kt
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/SAMLDownloadContext.kt
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/internal/BorrowSAMLDownload.kt
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/internal/BorrowSubtaskDirectory.kt
simplified-books-controller-api/build.gradle
simplified-books-controller-api/src/main/java/org/nypl/simplified/books/controller/api/BooksControllerType.kt
simplified-books-controller/src/main/java/org/nypl/simplified/books/controller/Controller.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/borrowing/BorrowSAMLDownloadTest.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/mocking/MockBorrowContext.kt
simplified-ui-catalog/build.gradle
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/saml20/CatalogSAML20Fragment.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/saml20/CatalogSAML20ViewModel.kt

This adds a SAML download context object to the borrowing context, to track information about the current SAML download. This is used by the SAML download subtask. When that subtask runs, it may find HTML content, which means that it should exit so that a login can happen in a webview. Once login is complete, the download subtask will run again, this time with a SAML download context that indicates that authentication is complete, and contains a different URL to use to retrieve the download. The download can then proceed with the new URL instead of the original.
Fixes an endless loop that can occur when doing SAML downloads: https://www.notion.so/lyrasis/Borrowing-from-SAML-testbed-causes-endless-loop-56303fd7b2044 …

Fix SAML download endless loop.

---

simplified-accounts-registry-api/src/main/java/org/nypl/simplified/accounts/registry/api/AccountProviderRegistryDebugging.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainServices.kt

This change makes the account registry debugging properties persistent
by using shared preferences. Typically we would _not_ use shared
preferences in the app, because they aren't profile-aware. In this
case, though, the debugging properties are truly app-global anyway.
Affects: https://www.notion.so/lyrasis/Android-build-that-can-persistently-uses-QA-library-registry-9874931996be425e8bbc378bcbbf3a1e
Check that the registry setting persists after an app restart.
Check that clearing the registry value results in a blank value after an app restart.
None.
**Has the application documentation …

Persist custom library registry to shared preferences

---

build.gradle
build_libraries.gradle
simplified-books-database/src/main/java/org/nypl/simplified/books/book_database/DatabaseFormatHandleAudioBook.kt

This upgrades to a version of the audio books API that will not fail
to parse positions that contain explicitly `null` titles. It also logs
an error and returns nothing instead of loudly raising an exception
if the saved position turns out to be malformed.
Affects: https://www.notion.so/lyrasis/Error-opening-app-after-exiting-from-audiobook-player-5694f5b2d40c4baea0d97782a3141cef
Try the behaviour in the ticket, and make sure the app no longer goes insane.
We shouldn't release a version of the app pointing at a snapshot version of the audiobook API. A new release should be tagged there if …

Do not fail if position parsing fails

---

simplified-webview/src/main/java/org/nypl/simplified/webview/WebViewCookieDatabase.kt
simplified-webview/src/main/java/org/nypl/simplified/webview/WebViewCookieDatabaseV10.kt
simplified-webview/src/main/java/org/nypl/simplified/webview/WebViewCookieDatabaseV12.kt
simplified-webview/src/main/java/org/nypl/simplified/webview/WebViewCookieDatabaseV13.kt
simplified-webview/src/main/java/org/nypl/simplified/webview/WebViewCookieDatabaseV14.kt
simplified-webview/src/main/java/org/nypl/simplified/webview/WebViewCookieDatabaseV9.kt
simplified-webview/src/main/java/org/nypl/simplified/webview/WebViewCookieDatabaseVUnknown.kt

Fixes a couple small issues with reading cookies out of the WebView cookie database.
- Modify cookie readers to only set the `domain` attribute when the `hostKey` starts with `.`.
- Add cookie readers for database versions 13 and 14.
Fixes: https://www.notion.so/lyrasis/e72462c871a54c5d9b8b4cbf740cfe2f?v=90916a8dfd7b4981bcb327f9362d7ea0&p=169e08657c8c4b21886a6a4fe0258883
This is not currently causing a problem, but I'm fixing now just in case.
SAML auth and borrowing should continue to work.
n/a
n/a
**Did someone …

Improve webview cookie handling in saml auth

---

README-CHANGES.xml
simplified-app-palace/src/main/java/org/thepalaceproject/palace/PalaceAccountFallback.kt
simplified-profiles/src/main/java/org/nypl/simplified/profiles/Profile.kt
simplified-ui-accounts/src/main/java/org/nypl/simplified/ui/accounts/AccountListRegistryViewModel.kt

This hides the default library from being seen by users.
1. Configure the default library to be a “fake” library (one whose uuid isn’t the same as any library in the registry). This makes every library in the registry able to be selected.
1. When a library is added, automatically delete the default library from the profile. Since the user must select a library when the app starts (and before they can do anything else), this means they never see the default library.
1. Filter the default library out of the library selection list, so it can’t be added by the user in the future.
Fixes: https://www.notion.so/lyrasis/DPLA-library-doesn-t-appear-in-library-selection-list-31741e673f594e74b7fc54da0dc78e00
Also, users not …

Hide the default library from users.

---

simplified-adobe-extensions/src/main/java/org/nypl/simplified/adobe/extensions/AdobeDRMServices.java
simplified-boot-api/src/main/java/org/nypl/simplified/boot/api/BootEvent.kt
simplified-boot-api/src/main/java/org/nypl/simplified/boot/api/BootLoader.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainAdobeWarnings.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainFragment.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainServices.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainServicesStrings.kt
simplified-main/src/main/res/values/stringsBoot.xml
simplified-ui-splash/src/main/java/org/nypl/simplified/ui/splash/BootFragment.kt

This updates the boot code and DRM service to check for and reject
expired certificates. It adds a new boot event type that allows for
displaying a dialog if something important but not fatal occurs on
boot, and then publishes an event if the DRM fails.
Affects: https://www.notion.so/lyrasis/Android-Properly-handle-expired-Adobe-certificate-427ab218209d40d3856246cb220fdbca
Affects: https://www.notion.so/lyrasis/App-crashes-on-login-when-Adobe-cert-is-expired-e71eda890b034802ae6ceab83d363d1a
If everything goes well, you should never see the effects of this code. If you want to see what happens, try using the currently-expired certificate. …

Gracefully handle expired certificates

---

README-CHANGES.xml
simplified-app-palace/build.gradle

This updates the hash of the Adobe certificate so that we can build using the updated certificate. Also updates the change log.
Our development certificate expired, so we got a new one.
Adobe DRM should be enabled, and reading Adobe-protected books should work.
n/a
n/a
@ray-lee ran the Palace app.

Update adobe cert.

---

simplified-reader-api/src/main/java/org/nypl/simplified/reader/api/ReaderPreferences.java
simplified-tests/src/test/java/org/nypl/simplified/tests/books/profiles/ProfileDescriptionJSONTest.kt
simplified-tests/src/test/resources/org/nypl/simplified/tests/books/profile-large-font-scale.json

Removes the constraint on the font scale when building reader preferences, which limits the value to be between 50 and 200.
This fixes a bug where the user can select a font scale greater than 200 in Readium, but it is limited to a max of 200 when the Readium settings are converted to user preferences. Since the user preferences are what get saved and restored when the user closes and re-opens the app, this causes the scale to be restored to 200, instead of the user's actual selection.
When the preferences are converted back to Readium settings, the font scale is already being constrained to the min and max values allowed by the Readium theme: https://github.com/ThePalaceProject/android-core/blob/04e0b9c26182dcd9f3 …

Remove constraint on font scale when building reader preferences.

---

simplified-ui-accounts/src/main/res/values/strings.xml
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFeedFragment.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFeedViewModel.kt
simplified-ui-settings/src/main/res/values/strings.xml

This adjusts all occurrences in the UI of the word "account" and
changes it to "library". This also adjusts the toolbar to display
the tab label rather than the library name.
Affects: https://www.notion.so/lyrasis/Android-Update-Title-menu-Bar-lable-to-for-view-names-vs-library-names-and-catalog-breadcrumbs-cfdfbdb03614475984eef1b70a937f3a
Affects: https://www.notion.so/lyrasis/Android-Update-UI-label-for-Accounts-to-Libraries-90cfef17026044549c7b55c3b50451a2
Check that you can't find the word Account in the UI.
Check that the toolbar displays generic terms such as "Catalog", "Books", etc. …

Accounts -> Libraries terminology

---

simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentListenerDelegate.kt

This adds some code to the main fragment listener delegate that
switches back to the catalog automatically when an account is created.
Affects: https://www.notion.so/lyrasis/Switch-library-catalog-when-adding-new-library-cc488ba037fa4704960b08cbd03262cc
1. Open the "Add a new library" screen
2. Select any library
3. Note that you're left looking at the Catalog, with the new library selected
None.
N/A
@io7m Tried it with a few libraries.

Automatically switch to catalog

---

simplified-viewer-epub-readium2/src/main/java/org/nypl/simplified/viewer/epub/readium2/Reader2Activity.kt

This creates a new instance of the tocFragment everytime the user enters the table of contents screen.
Affects: https://www.notion.so/lyrasis/e72462c871a54c5d9b8b4cbf740cfe2f?v=32b300218b974ecdb2054533a8b4a6d2&p=12cecd757c6a44db919e98009460fb4e
Open an ebook that has table of contents (**_Jane Eyre_** from Charlotte Brontë works)
Click on "Read"
Click on the top right icon
Select any chapter
Click on the top right icon
Select the same chapter as before and see it opens it
None.
N/A
**Did someone actually run this code …

Fixed TOC contents only working once

---

simplified-main/src/main/java/org/nypl/simplified/main/MainFragment.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentListenerDelegate.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailEvent.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailFragment.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailViewModel.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFeedFragment.kt

This adjusts how the toolbar is handled for book detail fragments and for other
screens. It fixes two main problems:
* The MainFragment's handling of the toolbar could override the handling
implemented by other fragments when the activity is resumed.
* The BookDetailFragment's handling of the toolbar was outright insufficient,
and didn't implement the proper back button behaviour.
Affects: https://www.notion.so/lyrasis/Toolbar-changes-when-going-back-from-epub-9db3750264324816987e4df1de8baebd
Affects: https://www.notion.so/lyrasis/Back-button-does-not-work-when-trying-to-go-back-from-Book-Details-View-fb88a9c983c64c09818dd2d88dc921b7
Try the …

Adjust toolbar handling

---

README-CHANGES.xml
build_libraries.gradle

Upgrade android-audiobook to the latest snapshot version.
This fixes long titles overlapping with the elapsed/total times when playing audiobooks. Notion: https://www.notion.so/lyrasis/Long-audiobook-chapter-titles-overlap-play-times-f5f1ee89fa204194a147ee24fd31dd18
Play "The Shadow Conspiracy" audiobook from Lyrasis Reads. On the player, the chapter title should appear on its own line, instead of the same line as the elapsed/total time displays. The chapter title should not overlap the times at all.
n/a
Yes
**Has the application documentation been …

Upgrade android-audiobook library

---

simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentDefaultViewModelFactory.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentListenedEvent.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentListenerDelegate.kt
simplified-ui-settings/src/main/java/org/nypl/simplified/ui/settings/SettingsDocumentViewerEvent.kt
simplified-ui-settings/src/main/java/org/nypl/simplified/ui/settings/SettingsDocumentViewerFragment.kt

This is a continuation of the toolbar adjustments from https://github.com/ThePalaceProject/android-core/pull/34 and https://github.com/ThePalaceProject/android-core/pull/37. It applies those adjustments to one more fragment that was previously missed.
This makes the back button functional again in the toolbars of the document viewer screens under Settings (User Agreement, Software Licenses, Privacy Policy).
In Settings, tap on the documentation items (User Agreement, Software Licenses, Privacy Policy). In the documentation viewer screen that opens, tap on the back button in the toolbar. The app should return to the Settings screen. …

Fix back button on document viewer screens.

---

README-CHANGES.xml
simplified-viewer-epub-readium2/src/main/java/org/nypl/simplified/viewer/epub/readium2/Reader2Activity.kt

This enables the newly added back button in the reader toolbar. The latest build of android-r2 adds a back button to the reader toolbar, which fires the `SR2ReaderViewNavigationClose` event. Currently, the `SR2ReaderViewNavigationClose` event handler assumes that the TOC is open, and all it does is attempt to close the TOC. This adjusts the handler to actually return to the previous screen when the TOC is not open.
This makes the toolbar behave more like it does on iOS. It also makes it easier for users to exit a book when the OS-provided back button is not enabled. Notion: https://www.notion.so/lyrasis/Add-back-button-to-reader-toolbar-0f25bf9b71fc4eae99b042a521d34c7e
**How should this be tested? / Do these …

Enable back button in reader toolbar.

---

simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogButtons.kt

This PR changes how the text size value is set to both textviews on the button with the missing loan duration and how the clock image layout parameters are initialized. Instead of using direct values, we use the converter in order to get the corresponding value in _sp_ (for the text size) and in _dp_ (for the image).
[A bug](https://www.notion.so/lyrasis/Time-left-on-loan-being-cutoff-on-Android-6bc0f1a88ff64e969c58ae651b7c61a2) was reported saying the missing loan duration text was being cropped in some devices with smaller screens.
Open the "Books" tab;
On the catalog, if you have books with loan durations (for instance, in Lyrasis library, …

Fix cropped button text on smaller devices

---

README-CHANGES.xml
simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentListenerDelegate.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentState.kt
simplified-ui-navigation-tabs/src/main/java/org/nypl/simplified/ui/navigation/tabs/TabbedNavigator.kt

This PR adds logic to better handle the way the app behaves after an user logs in to a library after performing an action on a book details screen. There's a new event that will specify if the user is requesting a login from a book details screen so the app can intercept it and redirect the user to the catalog tab (where the book details screen is still open) after successfully logging in.
There was a [task created on Notion](https://www.notion.so/lyrasis/e72462c871a54c5d9b8b4cbf740cfe2f?v=c5596de5b57d4027bf2984acfa70f930&p=8f17f0a85cd34af09c323397f2e993ea) saying that it could be misleading and a bad UX if the user returned to the catalog page after logging in from a book details screen without knowing if the …

Changed user redirect screen to a book details screen after logging in from there

---

README-CHANGES.xml
simplified-json-core/src/main/java/org/nypl/simplified/json/core/JSONParserUtilities.java
simplified-opds-core/src/main/java/org/nypl/simplified/opds/core/OPDSDateParsers.java
simplified-tests/src/test/java/org/nypl/simplified/tests/opds/OPDSFeedEntryParserTest.java
simplified-tests/src/test/resources/org/nypl/simplified/tests/opds/date-bug.xml

This switches the OPDS parser to consistently default to UTC
dates/times. Dates that explicitly specify time zones will use the
correct zones.
Affects: https://www.notion.so/lyrasis/Illegal-instant-due-to-time-zone-offset-transition-prevents-feed-from-displaying-42a4a9d280e841dfbbda67adf9631398
Check the OPDS entry in the referenced ticket.
None.
Yes.
N/A
@io7m Tried various books known to have the problem, and ran the test …

Always default to UTC for dates

---

simplified-opds-core/src/main/java/org/nypl/simplified/opds/core/OPDSAtom.java
simplified-opds-core/src/main/java/org/nypl/simplified/opds/core/OPDSXML.java

This completes the fix to always default to UTC when parsing dates in a feed (#66). It adds changes from the upstream fix (https://github.com/NYPL-Simplified/Simplified-Android-Core/pull/948) that were not included in #66.
Unit tests were failing after #66 was merged, because not all the changes from upstream were included. See #66 for the original motivation.
Unit tests should now pass. In the app, open some book details, and verify that the publish dates look reasonable. Also see #66. 
None
No, the changelog was updated in #66.
**Has the application …

Complete fix for defaulting feed dates to UTC.

---

README-CHANGES.xml
simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentDefaultViewModelFactory.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentListenedEvent.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentListenerDelegate.kt
simplified-ui-errorpage/build.gradle
simplified-ui-errorpage/src/main/java/org/nypl/simplified/ui/errorpage/ErrorPageEvent.kt
simplified-ui-errorpage/src/main/java/org/nypl/simplified/ui/errorpage/ErrorPageFragment.kt

This makes the back button in the toolbar on the error details screen work properly. This is a continuation of the toolbar adjustments from #34, #37, and #39. Hopefully the last!
Previously, tapping the back button on the error details screen would open the switch library menu, instead of returning to the previous screen. This made it hard for users to exit from the error details screen.
Notion: https://www.notion.so/lyrasis/Back-button-doesn-t-work-on-Error-Details-50d509d048dc4ca9a816db1735dbbe94
Do something that causes an error. As of this writing, attempting to "The Secret Language of Sisters" from LYRASIS Reads will do it. Tap the …

Fix back button on error details.

---

README-CHANGES.xml
simplified-app-openebooks/src/main/AndroidManifest.xml
simplified-app-palace/src/main/AndroidManifest.xml
simplified-app-simplye/src/main/AndroidManifest.xml
simplified-app-vanilla/src/main/AndroidManifest.xml

This PR sets the screen orientation as "Portrait" for every activity to disable the landscape mode.
There's a [task request](https://www.notion.so/lyrasis/Disable-landscape-mode-c4564cd3379e43b6be0ff0460fd5bcd6) to disable the landscape mode in order to fix some issues and to be aligned with the iOS app.
Open the app (make sure your device has the screen rotation enabled in the status bar options)
Go to every screen, rotate the device and verify the app is not rotating and the layout remains as it was
None
Yes
**Has the application documentation been …

Disabled landscape mode

---

README-CHANGES.xml
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFeedViewModel.kt

This PR changes the way we're handling the returning of the title on the catalog feed, i.e., instead of considering the type of feed (local or remote), we now just return the title of the received feed arguments, which will be "Catalog" for the generic Catalog" or the name of a clicked collection.
There's a [feature request](https://www.notion.so/lyrasis/Display-name-of-list-at-top-of-screen-on-Android-9ee236f3ab8c48e9953c4f2dfb8ecd99) to add this in order to be similar to the iOS app and to give the user a clearer idea of where's navigating.
Open the app
In the catalog tab, verify the [title is …

Added list name to top of screen

---

README-CHANGES.xml
simplified-reader-bookmarks-api/src/main/java/org/nypl/simplified/reader/bookmarks/api/ReaderBookmarkServiceUsableType.kt
simplified-reader-bookmarks/src/main/java/org/nypl/simplified/books/reader/bookmarks/internal/RBService.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/reader/bookmarks/NullReaderBookmarkService.kt
simplified-viewer-epub-readium2/src/main/java/org/nypl/simplified/viewer/epub/readium2/Reader2Bookmarks.kt

This syncs bookmarks (and the current reading position, which is a special bookmark) from the server when a book is opened in the readium epub viewer, prior to displaying the book and navigating to the current position. Previously, bookmarks were synced when the app was started, when changing libraries, and on an hourly schedule, but not when a book was opened.
The reading position within a book should be retained between devices. Previously, if a user read a book on device 1, then opened the book on device 2, the reading position would not be the same as on device 1, unless the user waited up to an hour for the next sync, or restarted the app, or changed to a different library and back. This forces the bookmarks …

Sync bookmarks when opening epub reader

---

README-CHANGES.xml
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogButtons.kt

This PR changes the text to display in some buttons. Instead of displaying "Get" for checked out books, it now displays "Download"
There's a [feature request](https://www.notion.so/lyrasis/e72462c871a54c5d9b8b4cbf740cfe2f?v=c5596de5b57d4027bf2984acfa70f930&p=b65bef98ec5d4fe289aeff6dfb5d64b5) to implement this in order to make it similar to the iOS version
Go to "My Books" tab
Verify [it now shows the 'Download' text](https://user-images.githubusercontent.com/79104027/148614201-77cec063-b08d-4eaf-a5e3-3457748f0fd3.png) for the checked out books
None
**Have you updated …

Changed "Get" to "Download" label in buttons

---

README-CHANGES.xml
simplified-ui-splash/src/main/java/org/nypl/simplified/ui/splash/SplashFragment.kt

This removes the EULA screen from the initial startup of the app.
This makes the Android app more similar to the iOS app, and makes the app more friendly to first-time users.
Notion: https://www.notion.so/lyrasis/Remove-end-user-agreement-from-the-first-screen-seen-before-tutorial-on-the-Android-app-ff33413b1076486cbdbad254abd4bc42
Uninstall the app, if you have it installed. Install the app, and run it. The app should immediately show the tutorial, without first showing the EULA.
None.
Yes.
**Has the application documentation been updated for these …

Don't show EULA screen on startup.

---

README-CHANGES.xml
simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentListenerDelegate.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBorrowViewModel.kt

This PR changes the tab where the user is coming from when entering the authentication screen for a library after trying to get a book on loan. This way, the user will stay in the settings tab if he log on to a library from there and will be redirected to the feed/book details screen after returning (logged in or not) from the auth screen (if the book required it). This PR also fixes the infinite loading bug that was happening if the user returned from the authentication screen to the book details page without logging in.
There's a [bug report indicating these two issues](https://www.notion.so/lyrasis/e72462c871a54c5d9b8b4cbf740cfe2f?v=c5596de5b57d4027bf2984acfa70f930&p=c72840a1fe73413f9f17f3a98f5a6e15) (infinite …

Fixed book title request infinite loading

---

README-CHANGES.xml
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/internal/BorrowLoanCreate.kt
simplified-books-registry-api/src/main/java/org/nypl/simplified/books/book_registry/BookStatus.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/borrowing/BorrowLoanCreateTest.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailFragment.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogPagedViewHolder.kt
simplified-ui-splash/src/main/java/org/nypl/simplified/ui/splash/SplashFragment.kt

This PR adds a flag (isOpenAccess) to the Loaned.NotDownloaded book status to distinguish the possible action between open access books and books from libraries that require authentication.
This change is being made so the user's experience can be clearer in terms of actions to perform over a book. Right now the app was either showing "Get" or "Download" for the books, and this way we can show "Get" when the user doesn't have downloaded the book and it is open access and we show "Download" when the user doesn't have downloaded the book and it isn't open access.
Go to the "Palace Bookshelf" library
Open any book and [verify …

Added 'isOpenAccess' flag to Loaned.NotDownloaded book status

---

README-CHANGES.xml
simplified-app-palace/build.gradle

This PR imports the Palace module to integrate Overdrive audiobooks. This also updates the expected sha-256 value for the secrets.conf file.
The audiobooks from Overdrive weren't being correctly downloaded and parsed, as reported [here](https://www.notion.so/lyrasis/Implement-support-for-OverDrive-Audiobooks-in-Android-3b9545183e2342e1a45f89e4a453e010). When opening an Overdrive audiobook, we would get [a downloading error](https://user-images.githubusercontent.com/79104027/149822730-3c778d71-8c42-4d00-bb3f-a2152fec55d3.png)
that was caused by [an incorrect manifest parsing](https://user-images.githubusercontent.com/79104027/149822787-2cf5ed9c-5612-413e-83e6-dd2ac0149c6f.png). This way, it's now possible to listen …

Added Palace Overdrive audiobooks integration module

---

README-CHANGES.xml
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookAvailabilityStrings.kt

This PR changes the borrow label information inside an open access book details page by considerating the book's open access status.
There's [a request](https://www.notion.so/lyrasis/Change-banner-text-for-open-access-titles-that-have-not-been-checked-out-886f0b5d538d4e3db61b0d9a3f1485e3) to make it as the iOS app currently has it and also for the user to not be confused by what the label says, because an open access book would say the book's currently loaned to the user even if the available action is "Get", which implies that it's not loaned to him
Open Palace app
Select "Palace bookshelf" library
Open any book
Verify [the available action …

Updated borrow label on open access books detail page

---

README-CHANGES.xml
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookPlayerActivity.kt

This PR changes the way the _AudiobookPlayerActivity_ handles the switch from the _PlayerFragment_ to the _TOCFragment_. Instead of replacing the first one, the activity hides it which will prevent it from being destroyed and to destroy the PlayerService. In this way, the behavior remains the same and the app doesn't crash when opening the TOC screen.
There's a [crash report](https://www.notion.so/lyrasis/Android-Tapping-in-ToC-for-audiobook-causes-app-to-crash-297b9396a30544ccafcd17174f3eba2f) saying that this was happening in some audiobooks, but the error could be most likely happening on every audiobook. By fixing this, the app doesn't crash anymore when the user opens the TOC screen.
**How should this be …

Fixed crash when opening the TOC page on audiobooks

---

README-CHANGES.xml
simplified-books-controller/src/main/java/org/nypl/simplified/books/controller/ProfileFeedTask.kt
simplified-feeds-api/src/main/java/org/nypl/simplified/feeds/api/FeedFacet.kt
simplified-profiles-controller-api/src/main/java/org/nypl/simplified/profiles/controller/api/ProfileFeedRequest.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFeedArguments.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFeedViewModel.kt
simplified-ui-navigation-tabs/src/main/java/org/nypl/simplified/ui/navigation/tabs/BottomNavigators.kt

This PR removes the 'Show' filter and the corresponding options from the "My Books" tab
[The "Show" filter is a bit redundant](https://www.notion.so/lyrasis/Remove-Show-filter-on-Android-17c955d0cfd64ce189ce5e81d847abd6) because the associated options ("All" and "On Loan") have no practical effect because all the books in the "My Books" tab are loaned to the user, so removing it will cause less complexity to the app.
Select "Lyrasis Reads" library
Open "My Books" tab
Verify [the "Show" filter option was removed](https://user-images.githubusercontent.com/79104027/150587137-2e382878-db97-4acb-b82b-8ca4aff7e0a9.png) and the …

Removed Show filter

---

README-CHANGES.xml
simplified-ui-accounts/src/main/java/org/nypl/simplified/ui/accounts/AccountAuthenticationViews.kt
simplified-ui-accounts/src/main/java/org/nypl/simplified/ui/accounts/AccountDetailFragment.kt
simplified-ui-accounts/src/main/res/layout/account.xml
simplified-ui-accounts/src/main/res/layout/auth.xml
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailFragment.kt

This PR adds logic to check if a library requires credentials in order to show or hide the sync bookmarks option. It also rearranges a bit the UI so, when the library doesn't require authentication, it doesn't look like [this](https://user-images.githubusercontent.com/79104027/152415534-d76fba2c-4855-45c9-b909-29400bf6deff.png). Finally, this PR also fixes the button action position in the book details page when it's reserved and can be removed, so it looks like [this](https://user-images.githubusercontent.com/79104027/152415745-a23d47a1-9625-488e-815b-ed24109d3d13.png).
There's a [ticket to remove the sync bookmark option](https://www.notion.so/lyrasis/Remove-Sync-Bookmarks-setting-for-Palace-Bookshelf-on-Android- …

Removed sync bookmarks option from libraries that don't require authentication

---

README-CHANGES.xml
simplified-books-controller/src/main/java/org/nypl/simplified/books/controller/BookRevokeTask.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/controller/BookRevokeTaskAdobeDRMTest.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/controller/BookRevokeTaskTest.kt

This removes books from the registry after they have been revoked (returned) and deleted from the database. It's basically the same fix as #62, added to another code path.
This fixes some books not being removed from My Books after they're returned. Notion: https://www.notion.so/lyrasis/Android-shows-already-returned-books-in-bookshelf-after-refresh-6b2f0d6e8afc4144af6b2dd48311034a
- In San Diego County Library, borrow a book, e.g. "The Woodlanders" by Thomas Hardy
- Open My Books, and confirm that the book appears
- Return the book
Verify that the book disappears from My Books.
Unit tests were updated.
**Dependencies for merging? Releasing …

Remove returned books from My Books

---

README-CHANGES.xml
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailViewModel.kt

This PR fixes an URI parsing that was making it unparseable by the app, leading to an error message when trying to open some book related books.
There's a [bug report](https://www.notion.so/lyrasis/Error-appears-when-you-try-to-open-related-books-6b840acfd4354598b75fb38dd647e51b) indicating that the books from the Palace Bookshelf are not allowing to open their related books feed.
Open the app
Select "Palace Bookshelf" library
Open any ebook
Scroll down and click on "Related books..."
Verify the feed [is being correctly opened](https://user-images.githubusercontent.com/79104027/152983229-07382453-de59-445d-bd5d-6a5bf2d4fea1.png) …

Fixed related books error

---

build.gradle
simplified-app-palace/build.gradle

This makes changes needed to use the production Readium LCP library:
- Our license key for the production library is stored in the secrets.conf file in mobile-certificates. The values in secrets.conf weren't previously available in build.gradle. This makes it so they are. (We've previously only made GitHub repo secrets available in build.gradle, but that doesn't seem to be the right place for this value, because it will be the same whether you're building locally or on CI). 
- The location of the LCP artifact is changed to the production location (which includes the license key) instead of the test location.
- The android-platform subproject is updated to change the version of the LCP library to 2.0.0 instead of 1.0.0. The 2.0.0 version appears to be the only one in …

Upgrade to production LCP library.

---

README-CHANGES.xml
simplified-viewer-pdf/src/main/java/org/nypl/simplified/viewer/pdf/PdfReaderActivity.kt
simplified-viewer-pdf/src/main/res/layout/pdf_reader.xml

This PR adds a toolbar with a back button to the pdf reader screen
There's a [bug report](https://www.notion.so/lyrasis/e72462c871a54c5d9b8b4cbf740cfe2f?v=22cd92c0cc5c46409134c9f380e6e718&p=5d703b8bfd334b148c77a4f9db216a8c) that says the user can't go back in the pdf reader screen. If he doesn't have the physical button on his device, he needs to close and reopen the app in order to get back to the catalog.
Open the app
Select "Lyrasis Reads" library
Open an ebook from Biblioboard, p.e., _Steven Universe #1 (Issue 1)_ by _Rebecca Sugar
Verify [the screen has a back button](https://user-images.githubusercontent.com/79104027/154706771-cfa45424-4 …

Added toolbar with back button to pdf reader

---

README-CHANGES.xml
simplified-opds-core/src/main/java/org/nypl/simplified/opds/core/OPDSAcquisitionFeedEntry.java
simplified-opds-core/src/main/java/org/nypl/simplified/opds/core/OPDSAcquisitionFeedEntryBuilderType.java
simplified-opds-core/src/main/java/org/nypl/simplified/opds/core/OPDSAcquisitionFeedEntryParser.java
simplified-tests/src/test/java/org/nypl/simplified/tests/opds/OPDSFeedEntryParserTest.java
simplified-tests/src/test/java/org/nypl/simplified/tests/opds/OPDSFeedParserTest.java
simplified-tests/src/test/java/org/nypl/simplified/tests/opds/OPDSJSONParserTest.java
simplified-tests/src/test/java/org/nypl/simplified/tests/opds/OPDSJSONSerializerTest.java
simplified-tests/src/test/resources/org/nypl/simplified/tests/books/loans.xml
simplified-tests/src/test/resources/org/nypl/simplified/tests/opds/compatibility-20180921-test-new-1.json
simplified-tests/src/test/resources/org/nypl/simplified/tests/opds/compatibility-20180921-test-old.json
simplified-tests/src/test/resources/org/nypl/simplified/tests/opds/entry-availability-loaned-timed.xml
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailFragment.kt
simplified-ui-catalog/src/main/res/values/stringsCatalog.xml

This PR adds the list of narrators (if available) to the information block inside the audiobook details page. This PR also updates the tests in order to include some verifications to the new added field.
There's [a feature request](https://www.notion.so/lyrasis/Display-narrator-information-for-audiobooks-Android-f17209776f284c1e87424a5334b83e36) stating that this information is available but isn't currently being displayed and the idea was to add it to the audiobook details page to make it more complete and to provide even more information to the user.
Open the app
Select the "Palace Marketplace Integration Library"
Choose any audiobook in …

Added narrators information to the book detail page

---

README-CHANGES.xml
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailFragment.kt
simplified-ui-catalog/src/main/res/layout/book_detail.xml
simplified-ui-catalog/src/main/res/layout/book_detail_metadata_item.xml

This PR replaces the _TableLayout_ container with a LinearLayout in order to make its child views display more than one line of information when it gets too large.
There's a comment and a [screenshot](https://user-images.githubusercontent.com/79104027/155736146-c6292691-ba52-4988-a747-3628ddd9ba48.png) in [this ticket](https://www.notion.so/lyrasis/Display-narrator-information-for-audiobooks-Android-f17209776f284c1e87424a5334b83e36) saying that in some books some of the information displayed in the details page is being cut off when it's too large. Apparently the _TableLayout_ has some bug regarding this because there's no specific limitation of the child lines but they keep getting cut off, so that's why it was …

Fix book details information being cut off

---

README-CHANGES.xml
simplified-app-palace/src/main/java/org/thepalaceproject/palace/PalaceBuildConfigurationService.kt
simplified-app-vanilla/src/main/java/org/nypl/simplified/vanilla/VanillaBuildConfigurationService.kt

This PR deletes the _Open Textbook Library_ uuid from the list of featured libraries.
There's a [request](https://www.notion.so/lyrasis/e72462c871a54c5d9b8b4cbf740cfe2f?v=22cd92c0cc5c46409134c9f380e6e718&p=d3d17099b64544ccae8f1467bda50a8b) to make this library disappear from the pinned libraries at the top and make it visible in the list below.
Open the app
Remove all the libraries from your account in order to test this "from the scratch" (you can also delete the app's storate in the device app settings)
Add a library
Verify there's just [one pinned library](https://user-images.githubusercontent.com/79104027/156194753-4b55837c-ccda-4241-8bf6- …

Remove Open Textbook Library from pinned libraries

---

README-CHANGES.xml
simplified-lcp/src/main/java/org/nypl/simplified/lcp/LCPContentProtectionProvider.kt
simplified-lcp/src/main/java/org/nypl/simplified/lcp/LCPHashedPassphrase.kt
simplified-tests/build.gradle
simplified-tests/src/test/java/android/util/Base64.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/lcp/LCPContentProtectionProviderTest.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/lcp/LCPHashedPassphraseTest.kt

This adds support for base-64 encoded LCP hashed passphrases. For LCP encrypted books in the loans feed, the `lcp:hashed_passphrase` element contains the hashed passphrase to be used as a key to decrypt the book. Currently, the CM sets this value to a hex string (a sha-256 hash). According to the spec, this value should be base64 encoded. The app will now check if a hashed passphrase is base64 encoded, and decode it if necessary, before using it as a key for decryption.
The LCP automatic key retrieval spec wants the hashed passphrase to be base64 encoded in transit:
https://readium.org/lcp-specs/notes/lcp-key-retrieval.html#sample-of-readium-web-publication-manifest-supporting-a-link-to-an-lcp-license-and-an-lcp_ha …

Decode base64-encoded LCP hashed passphrases.

---

README-CHANGES.xml
simplified-books-api/src/main/java/org/nypl/simplified/books/api/BookFormat.kt
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/internal/BorrowLCP.kt
simplified-books-database-api/src/main/java/org/nypl/simplified/books/book_database/api/BookDatabaseEntryType.kt
simplified-books-database-api/src/main/java/org/nypl/simplified/books/book_database/api/BookFormats.kt
simplified-books-database/src/main/java/org/nypl/simplified/books/book_database/DatabaseFormatHandleAudioBook.kt
simplified-books-formats-api/src/main/java/org/nypl/simplified/books/formats/api/StandardFormatNames.kt
simplified-books-formats/src/main/java/org/nypl/simplified/books/formats/BookFormatSupport.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/borrowing/BorrowLCPTest.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/borrowing/BorrowTestFeeds.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/controller/BookRevokeTaskTest.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/mocking/MockBookDatabaseEntry.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/mocking/MockBookDatabaseEntryFormatHandleAudioBook.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/mocking/MockBorrowContext.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/mocking/MockLCPService.kt

This adds support for borrowing and downloading LCP audiobooks (and eventually, PDFs).
- The `BorrowLCP` borrowing subtask only allowed the LCP acquisition path to result in an EPUB. It now allows the result to be an audiobook, and leaves a stub to allow supporting PDF.
- The `application/audiobook+lcp` mime type is now recognized, so that the LCP acquisition path will be followed.
This is the first step to support borrowing and playing LCP audiobooks. Notion: https://www.notion.so/lyrasis/Get-LCP-for-audiobooks-working-in-the-Palace-Android-app-46e982c74a2949d9b6049d6212a10380#dfb4e416ff57468eac0f993a0d9e3ec9
I've added unit tests for …

Add support for borrowing LCP audiobooks.

---

README-CHANGES.xml
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/internal/BorrowLCP.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainHTTP.kt

This fixes a timeout error when downloading large LCP audiobooks.
- The HTTP client timeout is increased to 5 minutes (from the default 1 minute).
- Error handling in `BorrowLCP.fulfill` is tweaked, so that a better error message appears on the Error Details screen when a download fails.
This addresses an error found in QA for the fix to remove the delay when opening LCP audiobooks. Notion: https://www.notion.so/lyrasis/Investigate-long-delay-when-opening-LCP-encrypted-audiobooks-900b5c8d8329417089e50ae4cfc14a13
Borrow and download a large LCP audiobook, e.g. "Goliath" in LYRASIS Reads. The download should complete successfully, although it …

Fix timeout downloading large audiobooks.

---

.ci-local/credentials.sh
README.md
build.gradle

This changes how the LCP production license key is obtained by gradle. Previously, the key was in Certificates/Palace/Android/secrets.conf in mobile-certificates, but it doesn't belong there, because the secrets.conf file is meant to only contain secrets needed by the app at runtime. The LCP production license key is only used at build time, in order to download the library using maven. The key now resides in LCP/prod_license_key.txt instead, and the build reads that file.
Note that for local builds, the property `org.thepalaceproject.app.credentials.palace` now must be set in gradle.properties. The value should be the path to the mobile-certificates repo. (This is similar to the`org.thepalaceproject.app.assets.palace` property, which should already be set.)
**Why are …

Read LCP license key from its own file instead of secrets.conf.

---

simplified-books-audio/src/main/java/org/nypl/simplified/books/audio/AudioBookOverdriveSecretServiceType.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainOverdriveSecretService.kt
simplified-tests/build.gradle
simplified-tests/src/test/java/org/nypl/simplified/tests/overdrive/MainOverdriveSecretServiceTest.kt

This makes the OverDrive client key and secret optional (nullable). The CM will be updated to provide the app with an OverDrive patron token to use for downloading OverDrive audio books, at which point the client key and secret won't be needed, and will be removed from the app. This ensures that the OverDrive service will continue to work when the key and secret are null.
Note: The CI build is failing because https://github.com/ThePalaceProject/android-audiobook-overdrive/pull/1 needs to be merged first.
Removing the OverDrive client credentials from the app improves security. Notion: https://www.notion.so/lyrasis/Android-Remove-need-for-OverDrive-client-key-and-secret-fbf7cf563def446dbb501fb7bcfa3a5a?d=9435e3d7bed …

Make OverDrive client key and secret optional.

---

README-CHANGES.xml
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/internal/BorrowLCP.kt
simplified-viewer-pdf/build.gradle
simplified-viewer-pdf/src/main/java/org/nypl/simplified/viewer/pdf/PdfReaderActivity.kt
simplified-viewer-pdf/src/main/java/org/nypl/simplified/viewer/pdf/PdfReaderParameters.kt
simplified-viewer-pdf/src/main/java/org/nypl/simplified/viewer/pdf/PdfViewerProvider.kt

This adds support for reading LCP-protected PDFs. These are downloaded as zip files, containing an encrypted PDF. Readium's kotlin-toolkit is used to open and decrypt the file, and pass an input stream to the reader.
Notion: https://www.notion.so/lyrasis/Add-support-for-LCP-encrypted-PDFs-Android-c14bd90d074941759ce038c62aa4a272#26d1b8829815434ab9f5dd452af46b23
In LYRASIS library, borrow and open "Spin Doctors" by Nora Loreto. The book should open successfully in the PDF reader. Other titles from the PDF Test lane may work, depending on the device, but they may be too large for the PDF reader to handle.
**Dependencies for merging? Releasing …

Add support for LCP-protected PDFs.

---

.gitignore
README-CHANGES.xml
simplified-books-audio/src/main/java/org/nypl/simplified/books/audio/UnpackagedAudioBookManifestStrategy.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentListenerDelegate.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailEvent.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailFragment.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailViewModel.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailViewModelFactory.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFeedViewModel.kt
simplified-ui-catalog/src/main/res/layout/book_detail.xml
simplified-ui-catalog/src/main/res/values/stringsFeed.xml

This PR adds the related books catalog to the book details screen. Instead of opening a new screen after clicking on "Related books...", the related books are now automatically loaded and shown in the screen.
There's a [feature request](https://www.notion.so/lyrasis/e72462c871a54c5d9b8b4cbf740cfe2f?v=1990931812bd44f29b28ce3b2aaeefad&p=af962b51273e434bbc821ac3b971c1ac) saying that this behavior should be implemented in order to replicate what we have in the iOS version.
Open the app
Select any library
Open any book
Scroll down and verify the related books are [being shown ](https://user-images.githubusercontent.com/79104027/162463778-ec07e783-8 …

Added related books feed to book details page

---

README-CHANGES.xml
simplified-books-audio/src/main/java/org/nypl/simplified/books/audio/UnpackagedAudioBookManifestStrategy.kt
simplified-books-covers/src/main/java/org/nypl/simplified/books/covers/BookCoverProvider.kt
simplified-books-covers/src/main/java/org/nypl/simplified/books/covers/BookCoverProviderType.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailFragment.kt
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookPlayerActivity.kt

This PR adds a boolean to set if the red icon should or should not appear at the bottom right corner of the audiobook cover image.
There's a [feature request](https://www.notion.so/lyrasis/Remove-red-audiobook-icon-from-covers-in-audiobook-player-3050fb51495e4286a228ebc978e9307a) to make the Android app similar to the iOS version to improve the UX
Open the app
Verify the audiobook [is showing the red icon](https://user-images.githubusercontent.com/79104027/162989594-6e86308c-e5dc-4f87-a0bd-b6e8a02f3f85.png) in the catalog
Open any audiobook
Verify the audioobook [is showing the red icon in the …

Removed red icon from audiobook cover in the audiobook player screen

---

simplified-tests/src/test/java/org/nypl/simplified/tests/books/audio/AudioBookSucceedingParsers.kt

This PR adds a missing _toc_ field to the PlayerManifest constructor in the AudioBookSucceedingParsers file.
The tests were failing
Run the pipeline and verify it doesn't return any errors
None
No
No

Added missing "toc" element

---

README-CHANGES.xml
simplified-app-palace/build.gradle

This updates the app to use a secrets.conf file that does not include the OverDrive client key and secret.
This improves the security of OverDrive downloads. Notion: https://www.notion.so/lyrasis/Android-Remove-need-for-OverDrive-client-key-and-secret-fbf7cf563def446dbb501fb7bcfa3a5a
From the OverDrive Integration Test Library, borrow and download audiobooks. The audiobooks should all download and play successfully.
https://github.com/ThePalaceProject/mobile-certificates/pull/20 must be merged first.
Yes
**Has the application documentation been updated …

Use updated secrets.conf without OD keys.

---

README-CHANGES.xml
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFeedFragment.kt
simplified-ui-catalog/src/main/res/layout/feed_content.xml
simplified-ui-catalog/src/main/res/values/stringsFeed.xml

This PR changes the way the facet buttons are created by removing their weight and setting their with to wrap their content. This also adds a condition to disable the searching button in the catalog in case the searching query is blank.
There are feature requests to [fix the bug where the facet labels are cropped](https://www.notion.so/lyrasis/Android-Sorting-of-books-The-title-of-the-button-Recently-Added-is-not-full-7cba041227a44379a848798f6bd4acb4) and also to [update the catalog searching behavior](https://www.notion.so/lyrasis/Android-Search-for-a-book-An-error-appears-when-the-search-field-is-empty-or-only-spaces-are-enter-3164edee27fb4f2389872788171b0349) to make it more similar to iOS.
**How should this be …

Fixed facet labels being cropped and catalog searching button behavior

---

README-CHANGES.xml
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/internal/BorrowLCP.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailFragment.kt

This PR forces the downloading status event to be sent before retrieving the book's passphrase when it's needed, so it can happen while a loading animation is displayed to the user instead of display the action buttons without any feedback
There's a reported bug saying that while the book's passphrase is being retrieved, the user sees the "Download" and "Return" buttons instead of a loading animation, which is misleading and causes a bad UX
Open the app
Open any book from the "DPLA Titles" section
Click on "Get"
Confirm you get [two loading animations: one for the LCP passphrase retrieval and the other for the …

Show loading indicator while LCP passphrase is being retrieved

---

README-CHANGES.xml
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailFragment.kt
simplified-ui-catalog/src/main/res/layout/book_detail.xml

This PR adds logic to get the number of lines the book description is filling after being set and in case it's higher than 6, it sets the maximum of lines to 6 and displays a "More" button that will display the full description when it's clicked.
There's a [feature request](https://www.notion.so/lyrasis/Android-There-is-no-More-button-in-the-book-detail-view-1632eebb651447ed97bbf8e0fd55afa4) to add this logic to make the app more similar to the iOS version
Open the app
Select "Palace Bookshelf" library (it can be other library)
Open _Macbeth_ by William Shakespeare (it can be other book)
Verify the [book's description is not fully visible and …

Added 'More' button to the book details screen

---

README-CHANGES.xml
simplified-ui-accounts/src/main/java/org/nypl/simplified/ui/accounts/AccountDetailFragment.kt
simplified-ui-accounts/src/main/res/layout/account.xml
simplified-ui-accounts/src/main/res/values/strings.xml

This PR adds logic to properly handle an url if an account's support email comes in that format instead of a regular email. If it's an url, a browser should be opened with the given link. If it's an email address, the behavior remains as it is. This also updates the text to display in case there's no installed browser on the user's phone.
There are some libraries that may set an url as a support email, as stated [here](https://www.notion.so/lyrasis/Android-Change-support-email-field-to-support-URLs-d2050a378112466e9c9025d9feecaad2), and the apps should adapt to that.
For now, as far as I know, there are no libraries with an url as a support …

Added support to urls in an account's support email field

---

README-CHANGES.xml
simplified-accessibility/src/main/java/org/nypl/simplified/accessibility/AccessibilityService.kt
simplified-accessibility/src/main/java/org/nypl/simplified/accessibility/AccessibilityStrings.kt
simplified-accessibility/src/main/java/org/nypl/simplified/accessibility/AccessibilityStringsType.kt
simplified-accessibility/src/main/res/values/strings.xml
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/BorrowContextType.kt
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/BorrowTask.kt
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/internal/BorrowLoanCreate.kt
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/subtasks/BorrowSubtaskException.kt
simplified-books-controller/src/main/java/org/nypl/simplified/books/controller/ProfileFeedTask.kt
simplified-books-registry-api/src/main/java/org/nypl/simplified/books/book_registry/BookStatus.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/borrowing/BorrowLimitLoanTest.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/mocking/MockAccessibilityStrings.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/mocking/MockBorrowContext.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookAvailabilityStrings.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailFragment.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailViewModel.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFeedViewModel.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogPagedViewHolder.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogPagedViewListener.kt
simplified-ui-catalog/src/main/res/values/stringsCatalog.xml

This PR adds a new state for a book borrowing result: the BookReachedLoanLimit. In order to assign it, we're comparing the error report type and then broadcasting the new status. Whenever the views receive this state, they'll immediately call their viewModel method to restore the book initial status so the options can be the same as they were before the book borrowing request and they'll display a dialog with the proper message.
There's a [feature request](https://www.notion.so/lyrasis/Android-There-is-an-error-instead-of-alert-when-the-limits-of-books-for-loan-are-exceeded-b3e8d307daec41d580c97733dd58a38e) to make this behavior similar to the iOS version.
**How should this be tested? / Do these changes have …

Added dialog with the loan limit message

---

README-CHANGES.xml
simplified-ui-accounts/src/main/java/org/nypl/simplified/ui/accounts/AccountPickerDialogFragment.kt

This PR adds a "Cancel" option to the library selection dialog
There's a [feature request](https://www.notion.so/lyrasis/e72462c871a54c5d9b8b4cbf740cfe2f?v=7669bb698f0b4f7486211f75d6170b17&p=157fa0c2bdac427292d6e74ce240dd98) to make this change so it gets similar to the iOS version of the app
Click on the logo on the top left corner
Verify [there's a "Cancel" option at the bottom of the dialog](https://user-images.githubusercontent.com/79104027/179277576-5ce07e5e-357a-4c36-9ccb-1bc614b19a87.png)
Click on it and verify the dialog closes
None
**Have you updated the …

Added 'Cancel' option to library selection dialog.

---

README-CHANGES.xml
simplified-profiles-api/src/main/java/org/nypl/simplified/profiles/api/ProfilePreferences.kt
simplified-profiles/src/main/java/org/nypl/simplified/profiles/ProfileDescriptionJSON.kt
simplified-profiles/src/main/java/org/nypl/simplified/profiles/ProfilesDatabases.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/profiles/ProfileDescriptionJSONTest.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/mocking/MockProfile.kt
simplified-tests/src/test/resources/org/nypl/simplified/tests/books/profile-rates.json
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookPlayerActivity.kt

This PR adds a field called _playbackRates_ to the profile preferences so the user can save all of their audiobook's playback rates. When listening to an audiobook, a new entry is added to that new field with the BookID and the playback rate so it can be restored when reopening that same audiobook
There's a [ticket with a bug](https://www.notion.so/lyrasis/e72462c871a54c5d9b8b4cbf740cfe2f?v=7669bb698f0b4f7486211f75d6170b17&p=0f3ab653edd54965bc9f9280702eea47) that says the audiobook's playback rate is not saved when the user closes the book and they need to set it again when reopening the book.
_This can only be tested when [this …

Added playbackRates to profile preferences

---

README-CHANGES.xml
simplified-ui-accounts/src/main/res/layout/account_cell.xml

This PR removes the line limit for both account title and subtitle on the account details screen.
There's a [ticket](https://www.notion.so/lyrasis/Android-Library-name-does-not-wrap-on-the-Account-page-in-app-f192d27905fb4cc991fd45dcab46f15f) with a bug saying that on the account details screen when an account has a large name it's not being fully displayed.
Open the app
Go to Hopkinsville Christian County Public Library
Go to their account page
Verify [the account name is being fully displayed](https://user-images.githubusercontent.com/79104027/181605438-18d94b85-7527-47da-9cf2-bca9a8872212.png) …

Fixed account name not being fully displayed on account details screen.

---

README-CHANGES.xml
simplified-bookmarks-api/src/main/java/org/nypl/simplified/bookmarks/api/BookmarkServiceUsableType.kt
simplified-bookmarks/src/main/java/org/nypl/simplified/bookmarks/internal/BService.kt
simplified-bookmarks/src/main/java/org/nypl/simplified/bookmarks/internal/BServiceOpCreateLocalBookmark.kt
simplified-bookmarks/src/main/java/org/nypl/simplified/bookmarks/internal/BServiceOpCreateRemoteBookmark.kt
simplified-main/src/main/java/org/nypl/simplified/main/MainServices.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/bookmarks/NullBookmarkService.kt
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookPlayerActivity.kt
simplified-viewer-epub-readium2/src/main/java/org/nypl/simplified/viewer/epub/readium2/Reader2Activity.kt

This PR divides the bookmark saving concept into two different ways: local and remote. By doing that, we can exit the player screen and just save the bookmark remotely because now it'll be locally saved every second (implemented on [this PR](https://github.com/ThePalaceProject/android-audiobook/pull/38)).
There's [a ticket with a bug](https://www.notion.so/lyrasis/Android-Last-reading-position-is-not-saved-after-reopening-the-audiobook-from-Biblioboard-or-Palac-b1ea2ca76af54449aa05b22f5d598f88) saying that some audiobooks are not storing the last position after exiting the player screen.
_Note: The PR can only be tested when [this …

Fixed audiobook bookmarks not being saved after exiting the player.

---

README-CHANGES.xml
simplified-books-controller-api/src/main/java/org/nypl/simplified/books/controller/api/BooksControllerType.kt
simplified-books-controller/src/main/java/org/nypl/simplified/books/controller/BookRevokeTask.kt
simplified-books-controller/src/main/java/org/nypl/simplified/books/controller/Controller.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailViewModel.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBorrowViewModel.kt

This PR changes the way the CatalogBookViewModel recreates a "book with a status" after returning it. Instead of using the _feedEntry_ from the initial parameters, now it uses an updated feed entry that's retrieved after returning the book.
There's a [ticket with a bug](https://www.notion.so/lyrasis/There-s-an-error-trying-to-get-a-book-after-returning-it-from-My-Books-tab-370a14f9163d483885d7da4d987d40a3) explaining and showing how this bug is happening and it should be fixed so the user can get the book again directly from its details screen on the"My Books" tab instead of having to go to the catalog to retrieve it again.
You can follow the …

Fix broken state after returning a book.

---

README-CHANGES.xml
simplified-ui-neutrality/src/main/java/org/nypl/simplified/ui/neutrality/NeutralToolbar.kt
simplified-ui-neutrality/src/main/res/values/strings.xml

This PR adds a content description to the back button / logo image on the toolbar. When setting the toolbar's imageview image, we verify if it's the back button or the app's logo and set its content description according to it
There's a [ticket with a bug](https://www.notion.so/lyrasis/Android-There-is-an-unlabeled-button-on-the-book-detail-view-screen-2fbc0a5aa61545e78fede8ce86dbf4aa) saying that the back button of the toolbar doesn't display a "Text" value when selecting on the inspect mode of the BrowserStack.
The [BrowserStack now displays the "Back" label](https://user-images.githubusercontent.com/79104027/183928158-0a269d52-d9f8-405e-b50 …

Added 'content description' text to back button and logo on toolbar.

---

README-CHANGES.xml
simplified-main/src/main/res/layout/main_host.xml
simplified-ui-accounts/src/main/res/menu/account_list_registry.xml
simplified-ui-neutrality/src/main/java/org/nypl/simplified/ui/neutrality/NeutralToolbar.kt

This PR sets a fixed height to the Toolbar so on the "Add Library" screen opening the SearchView doesn't cause the Toolbar's height to be improperly increased. By doing that, there was the need of removing one of the actions from the SearchView in the XML to make the UI consistent. After that, when opening the SearchView, there were two buttons: the Toolbar's back button and the SearchView clear text button. Both of them should have the same action, i.e., close the SearchView when it's open, so there was also the need of changing the Back button clicking action by checking if the toolbar has a SearchView that's not iconified, i.e., that's open.
There's a [ticket with a …

Added back button when search field appears

---

README-CHANGES.xml
simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentListenerDelegate.kt
simplified-profiles-api/src/main/java/org/nypl/simplified/profiles/api/ProfilePreferences.kt
simplified-profiles/src/main/java/org/nypl/simplified/profiles/ProfileDescriptionJSON.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/pdf/PdfViewerProviderTest.kt
simplified-ui-settings/src/main/java/org/nypl/simplified/ui/settings/SettingsDebugFragment.kt
simplified-ui-settings/src/main/java/org/nypl/simplified/ui/settings/SettingsDebugViewModel.kt
simplified-ui-settings/src/main/res/layout/settings_debug.xml
simplified-ui-settings/src/main/res/values/strings.xml
simplified-viewer-pdf-pdfjs/src/main/java/org/nypl/simplified/viewer/pdf/pdfjs/PdfViewerProvider.kt
simplified-viewer-pdf/src/main/java/org/nypl/simplified/viewer/pdf/PdfViewerProvider.kt

This PR sets the PDF-JS reader as the default PDF reader and updates the dev settings so the user can set the old PDF reader if they want
The PDF-JS reader seems to be stable and working very well so there's a [feature request](https://www.notion.so/lyrasis/Android-Promote-new-PDF-reader-to-be-the-default-reader-912b0a24b12042fcbf444f1c237902ec) to promote it as the default reader.
Choose "LYRASIS Reads" library
Open a pdf book from _New Biblioboard Test_ lane
Confirm the pdf reader [is the PDF-JS reader](https://user-images.githubusercontent.com/79104027/186181938-3e88af4b-0825-47d8-8b08-f79b3fedf283.png)
Go to settings …

Switched default PDF reader to the PDF-JS Reader

---

README-CHANGES.xml
simplified-ui-accounts/src/main/java/org/nypl/simplified/ui/accounts/AccountListRegistryFragment.kt

This PR adds logic to calculate the available width for the SearchView and set it as its maximum width value.
There's been found [a bug in some devices](https://www.notion.so/lyrasis/Android-The-back-arrow-disappears-when-the-search-field-appears-cc14886f53fb4154a8c4327f27491f3b) where the searching field overlaps the back button or is very close to it, which doesn't look good in terms of UI
Go to Settings
Click on Libraries
Click on the + at the top right
Click on the searching icon
See the searching field is not overlapping anything
_Note: In order to reproduce the reported bug, there are some devices listed in [this …

Fixed searching field text overlapping back button

---

README-CHANGES.xml
simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentListenerDelegate.kt
simplified-ui-accounts/src/main/java/org/nypl/simplified/ui/accounts/AccountListRegistryEvent.kt
simplified-ui-accounts/src/main/java/org/nypl/simplified/ui/accounts/AccountListRegistryFragment.kt
simplified-ui-onboarding/src/main/java/org/nypl/simplified/ui/onboarding/OnboardingFragment.kt

This PR changes the way the back button actions are handled. When the user goes to the account selection from the catalog, we're now overriding the logo click action so the app can perform the action of returning to the catalog. When the user is on the onboarding screen and wants to choose a library, the account list screen is now being removed from the fragment manager so the user can return to the previous screen. Also, this PR changes the source tab that called the account list screen as it can be opened from two different areas: the Catalog and the Settings.
There's a [reported bug](https://www.notion.so/lyrasis/Android-The-Back-button-doesn-t-return-to-the-Catalog-screen-a21a148239e34935a70794bf697644c9) …

Fixed back button action on some screens

---

README-CHANGES.xml
simplified-viewer-pdf-pdfjs/src/main/java/org/nypl/simplified/viewer/pdf/pdfjs/PdfReaderActivity.kt

This PR checks if the PDF Viewer WebView has been initialized before applying any of the selected options by the user. When the PDF is loading, the user may already select the Settings or TOC options and if the WebView hasn't been initialized yet nothing should happen.
There's a [reported bug](https://www.notion.so/lyrasis/Android-PDF-There-is-a-redirection-to-the-Catalog-or-the-app-stops-when-we-tap-TOC-or-Settings-str-f441d733c81e4486b8425d000652c6ee) saying the app is crashing when selecting the TOC/Settings option while the PDF is being loaded.
Select "LYRASIS Reads"
Search for "Who lives in a tree"
Download the PDF …

Fixed app crashing when opening TOC or settings before loading the PDF

---

README-CHANGES.xml
simplified-viewer-pdf-pdfjs/src/main/java/org/nypl/simplified/viewer/pdf/pdfjs/PdfReaderActivity.kt
simplified-viewer-pdf-pdfjs/src/main/res/values/strings.xml
simplified-viewer-pdf/src/main/java/org/nypl/simplified/viewer/pdf/PdfReaderActivity.kt
simplified-viewer-pdf/src/main/res/values/strings.xml

This PR adds a content description to the back button on the toolbar of the reader screen.
There's a [ticket with a bug](https://www.notion.so/lyrasis/Android-There-are-unlabeled-buttons-on-the-book-reading-and-listening-screens-1847df33398945e487c8f0e6b3a136df) saying that the back button of the reader's toolbar doesn't display a "Text" value when selecting on the inspect mode of the BrowserStack.
The [BrowserStack now displays the "Back" label](https://user-images.githubusercontent.com/79104027/192505454-7dd41e87-dcdb-4fd3-9846-449329c60a01.png) on the Inspect Mode, but this can be tested by:
1. Turn the TalkBack feature of the phone in the …

Added content description to back button on reader screen

---

README-CHANGES.xml
simplified-ui-accounts/src/main/java/org/nypl/simplified/ui/accounts/AccountDetailFragment.kt

This PR removes two lines of code that had impact on how the UI behaves in the account detail screen when the user send the app to background. There's no point in clearing the views list and setting the image to null and when the user returns those two objects weren't restored, which was causing the login button to being disabled and the account logo image to disappear.
There's a comment in [this ticket](https://www.notion.so/lyrasis/Android-Investigate-the-cases-of-Log-in-button-unavailability-f3dfc83441c54ba79618a2c5c08e7e85) saying the login button is disabled when reentering the app
Select a library where you're logged …

Fixed login button being disabled when reentering the app

---

README.md
build.gradle
simplified-books-borrowing/build.gradle
simplified-main/build.gradle
simplified-tests/build.gradle

This is a refinement of #145, to avoid breaking PR builds.
This moves the configuration for downloading the LCP decryption library into an external script. It also removes dependencies on the LCP library from modules where it wasn't being used, so that the only remaining use is in `simplified-app-palace`.
This makes the LCP build recipe private. Notion: https://www.notion.so/lyrasis/Move-LCP-recipe-to-properties-c508747ff48b416a9a6f31096e1f8e03
Verify that LCP books (e.g. epubs from the DPLA Titles lane in LYRASIS Reads, such as "The Great Illyrian Revolt" can be downloaded. …

Externalize LCP build configuration.

---

README-CHANGES.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties
simplified-app-palace/src/main/AndroidManifest.xml
simplified-cardcreator/build.gradle
simplified-reports/build.gradle
simplified-tests-sandbox/build.gradle
simplified-ui-catalog/build.gradle
simplified-ui-splash/build.gradle

This updates the app to target Android 12 (API 32), including necessary dependency and gradle upgrades.
It also includes a workaround for the currently failing readium nanohttpd artifact downloads, which can be removed when that problem is fixed by readium.
Apps will be required to target Android 12 in November. Notion: https://www.notion.so/lyrasis/Update-Android-app-to-target-Android-13-2d0216494ad846579321de4b5a4c932f
Basically the whole app should be tested to make sure everything looks good. Looking at the Android 12 release/upgrade docs, there are only a couple areas of concern:
- There was a change to cookie handling that may affect …

Target Android 12 (API 32).

---

README-CHANGES.xml
build.gradle
simplified-cardcreator/src/main/java/org/nypl/simplified/cardcreator/ui/LocationFragment.kt
simplified-viewer-pdf-pdfjs/build.gradle

This updates the app to target Android 13 (API 33).
Some additional null checks that are now needed have been added.
It also removes the workaround for the failing readium nanohttpd artifact downloads, since that problem has been fixed by readium.
Notion: https://www.notion.so/lyrasis/Update-Android-app-to-target-Android-13-2d0216494ad846579321de4b5a4c932f
Basically the whole app should be tested to make sure everything looks good. Looking at the Android 13 release/upgrade docs, there are only a couple areas of concern:
- There were some changes to the media player on the lock screen/notification area. Audiobook playback and controls should …

Target Android 13 (API 33).

---

README-CHANGES.xml
simplified-ui-accounts/src/main/res/values/strings.xml
simplified-ui-profiles/src/main/res/values/stringsProfiles.xml

This PR updates some sign in and sign out related labels
There's a comment in [this ticket](https://www.notion.so/lyrasis/Change-Log-out-to-Sign-out-and-Log-in-to-Sign-in-on-Android-46c86aec81d14f28b063e5dfcb5cb6b6) requesting to change the "Sign Out" to "Sign out" and "Sign In" to "Sign in
Go to "Settings" and then "Libraries"
Select a library that requires authentication
Confirm the button now says "Sign In" instead of "Log in"
Enter your credentials and sign in
Confirm the button now says "Sign Out" instead of "Log out"
None
Yes …

Updated sign in and sign out labels

---

README-CHANGES.xml
simplified-ui-accounts/src/main/res/layout/account.xml
simplified-ui-accounts/src/main/res/layout/auth_coppa.xml
simplified-ui-neutrality/src/main/res/values/styles_common.xml
simplified-ui-settings/src/main/res/layout/settings_debug.xml

This PR changes the enabled color of all the Switch elements in the app.
There's a [feature request](https://www.notion.so/lyrasis/Android-Add-green-color-or-other-indicator-that-sync-bookmarks-is-enabled-1a47cff8e1634cc6af2f59f0ae076d93) saying the enabled color of the Switch should be different from what we got since it's hard to tell if it's enabled or not.
Go to Settings
Go to Libraries
Open, for example, the Lyrasis Reads library
Enable the "Sync Bookmarks" switch if it's not enabled
Confirm [the color of the "Sync Bookmarks" is now green](https://user-images.githubusercontent.com/79104027/205410132-4d8d1046-3d7c-4988- …

Changed the Switch's enabled color to green

---

README-CHANGES.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

This PR downgrades the used Gradle versions to the ones before [this PR](https://github.com/ThePalaceProject/android-core/pull/149)
After merging [this PR](https://github.com/ThePalaceProject/android-core/pull/149) I couldn't build the Palace app anymore and it's somehow related to that. Since several weeks have been gone and the building issues remain and this change doesn't impact the app's behavior, me and @ray-lee talked about downgrading the version
The app should compile and run without any issues
None
Yes
**Has the application documentation been …

Downgrade Gradle version

---

README-CHANGES.xml
simplified-app-palace/src/main/java/org/thepalaceproject/palace/PalaceDocumentStoreConfiguration.kt
simplified-documents/src/main/java/org/librarysimplified/documents/DocumentConfiguration.kt
simplified-documents/src/main/java/org/librarysimplified/documents/internal/AbstractDocument.kt
simplified-documents/src/main/java/org/librarysimplified/documents/internal/DocumentStore.kt
simplified-documents/src/main/java/org/librarysimplified/documents/internal/EULA.kt
simplified-documents/src/main/java/org/librarysimplified/documents/internal/PlainDocument.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/documents/DocumentStoreTest.kt
simplified-ui-settings/src/main/res/values/strings.xml

This PR adds the "About Palace" option to the Settings screen and changes the way how a preference is opened. If the document configuration's name is not null or blank, then the behavior remains the same, but if it's name or file are null, then the returned URI is the _remoteURI_ so it can be opened and handled by the WebView instead of opening a local file.
There's a [feature request](https://www.notion.so/lyrasis/Android-There-is-no-an-About-Palace-item-0d3449f757bc4be2a7d08017f58223e8) to include this option on the settings of the Android app as it's already on the iOS settings screen.
Go to Settings
Confirm the ["About …

Added "About Palace" option to Settings screen

---

README-CHANGES.xml
simplified-app-palace/src/main/AndroidManifest.xml
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookPlayerActivity.kt

This PR adds support to the new method from the Audiobook submodule and returns the intent that should be opened when clicking on the audiobook's player notification
There's a [feature request](https://www.notion.so/lyrasis/Android-There-is-no-redirection-to-the-app-from-an-audiobook-playback-screen-in-notification-area-62d04cd1384e438a9fdb5d6bf605288b) saying the current audiobook player notification does nothing when it's clicked and it should redirect the user to the app.
Reproduce the same steps than [here](https://github.com/ThePalaceProject/android-audiobook/pull/53)
[This …

Added ability to open the app when clicking on the audiobook's player notification

---

README-CHANGES.xml
simplified-profiles-api/src/main/java/org/nypl/simplified/profiles/api/ProfilePreferences.kt
simplified-profiles/src/main/java/org/nypl/simplified/profiles/ProfileDescriptionJSON.kt
simplified-profiles/src/main/java/org/nypl/simplified/profiles/ProfilesDatabases.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/profiles/ProfileDescriptionJSONTest.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/mocking/MockProfile.kt
simplified-tests/src/test/resources/org/nypl/simplified/tests/books/profile-sleep-timers.json
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookPlayerActivity.kt

This PR adds logic to support, save and update the sleep timer values set by the user for each audiobook
There's a [feature request](https://www.notion.so/lyrasis/Audiobook-sleep-timer-not-saved-after-closing-book-bab815834a374893a0588ca96fc8caa7) saying the sleep timer is not being restored when the user sets it and closes and reopens the book.
When [this PR](https://github.com/ThePalaceProject/android-audiobook/pull/54) is merged, reproduce the testing steps
[This PR](https://github.com/ThePalaceProject/android-audiobook/pull/54) needs to be merged first
**Have you updated the …

Added sleepTimers to profile preferences

---

README-CHANGES.xml
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFeedFragment.kt
simplified-ui-catalog/src/main/res/menu/catalog.xml
simplified-ui-neutrality/src/main/java/org/nypl/simplified/ui/neutrality/NeutralToolbar.kt

This PR updates the logic of searching with a feed catalog by replacing the searching dialog with the native searchview on the toolbar so the current search query can be displayed when the results are shown. This PR also updates the method of calculating the available width to be filled by the SearchView
There's a [feature request](https://www.notion.so/lyrasis/Android-The-search-bar-is-not-displayed-when-the-search-result-is-opened-a610c54b37b342d0a910589f826bbb85) saying the Android app is not displaying the current search query to the user on the search bar and the Android app should match the iOS version regarding this functionality.
Open …

Display the search query on the search bar

---

simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFeedFragment.kt

This PR updates the Readium submodule version and automatically closes the keyboard after performing a new search.
Regarding the Readium version, one of the latest changes on the Readium submodule is not being seen on the Palace app. Regarding a new search, there was a comment on [this ticket](https://www.notion.so/lyrasis/Android-The-search-bar-is-not-displayed-when-the-search-result-is-opened-a610c54b37b342d0a910589f826bbb85) suggesting this feature to be implemented
_Readium:_
Reproduce the steps of [this PR](https://github.com/ThePalaceProject/android-r2/pull/18/files)
_New search:_
Select any library
Perform any …

Updated Readium version and automatically close the Keyboard after performing a search

---

README-CHANGES.xml
simplified-profiles-api/src/main/java/org/nypl/simplified/profiles/api/ProfilePreferences.kt
simplified-profiles/src/main/java/org/nypl/simplified/profiles/ProfileDescriptionJSON.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/profiles/ProfileDescriptionJSONTest.kt
simplified-tests/src/test/resources/org/nypl/simplified/tests/books/profile-sleep-timers.json
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookPlayerActivity.kt

This PR updates the existing logic to save/restore the current audio book sleep timer value but it now updates the value every time the timer changes so the remaining duration can be stored and the timer doesn't get restarted every time the audiobook is opened.
There's a comment in [this ticket](https://www.notion.so/lyrasis/Audiobook-sleep-timer-not-saved-after-closing-book-bab815834a374893a0588ca96fc8caa7) saying the timer shouldn't be restarted when reopening the audiobook but resumed.
Follow [this PR](https://github.com/ThePalaceProject/android-audiobook/pull/55) testing steps once that and [this …

Updated audiobook sleep timer stored value so the can be resumed

---

simplified-tests/src/test/java/org/nypl/simplified/tests/books/controller/BookRevokeTaskTest.kt

This PR increases the timeout of a failing test becauase the test itself hasn't been changed in a really long time, so the timeout value may be too low and it's causing the test to fail.
The Main branch pipelines are failing because of this test.
The pipeline should successfully run
None
No
No

Fixed failing test

---

README-CHANGES.xml
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailFragment.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogPagedViewHolder.kt

This PR updates the button creation logic to place the "Remove" after the "Get" button on a book reservation item.
There's a [feature request](https://www.notion.so/lyrasis/Android-Get-button-doesn-t-appear-first-in-the-Reservations-tab-92d7261bfe974a2ea42aea527b7e616b) saying the iOS app has the buttons in a different order than the Android app and they should have both the same order.
If you already have a book reservation that is available, go to the "Reservations" tab and confirm the "Get" button appears before the "Remove" button
If you have no reservations at all, reserve a book and …

Change position of 'Remove' button

---

README-CHANGES.xml
simplified-ui-catalog/src/main/res/layout/book_detail.xml
simplified-viewer-preview/src/main/java/org/nypl/simplified/viewer/preview/BookPreviewEmbeddedFragment.kt
simplified-viewer-preview/src/main/res/layout/fragment_book_preview_audiobook.xml
simplified-viewer-preview/src/main/res/layout/fragment_book_preview_embedded.xml

This PR updates the preview webview's WebChromeClient in order to handle some of the available commands. This also changes the webview and audiobook preview screens' toolbar back button color and fixes the audiobook preview's webview not being destroyed when returning from that screen.
There was a [bug report](https://www.notion.so/lyrasis/Investigate-options-for-controlling-reader-for-Palace-Marketplace-previews-f04fb983e0f34f448bfab59bd424170f) saying the webview commands were not working for some previews. I've also noticed the audiobook and webview's preview screen back button color weren't properly set. There's also a [bug report](https://www.notion.so/lyrasis/OverDrive-audiobook-preview-keeps-playing-after-ex …

Fixed book preview webview commands not working

---

.github/workflows/android-main.yml
.github/workflows/android-pr.yml
.github/workflows/android-release.yml

This upgrades github actions that are used in our workflows to versions that use Node 16 instead of Node 12.
GitHub is disabling actions that use Node 12, which causes this warning when we run actions:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-java@v1, actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
CI builds should continue to run successfully. The Node.js 12 warning should no longer appear. …

Upgrade actions to use node 16.

---

.github/workflows/android-main.yml
.github/workflows/android-pr.yml
.github/workflows/android-release.yml

This is a follow-up to #171. In that PR I upgraded setup-java from v1 to v2, but I should have gone to v3, in order to use Node 16.
GitHub is disabling actions that use Node 12, which causes this warning when we run actions:
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-java@v1, actions/upload-artifact@v2. For more information see: **https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.**
CI builds should continue to run successfully. The Node.js 12 warning should no longer appear.
**Dependencies for …

Upgrade setup-java action to v3.

---

README-CHANGES.xml
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookPlayerActivity.kt

Save listening position on play, pause, and stop
Reduce server load
https://www.notion.so/lyrasis/Android-Save-listening-position-less-frequently-ff7c6dc43caa492d98105a48e56d4c26
Open an audiobook, navigate to another chapter in the book. Exit the audiobook and open the same audiobook within the same account on a different device and confirm the bookmark was saved.
You can also confirm that locations within chapters are saved and synced between different devices, in the same book and same account. 
Related to: https://github.com/ThePalaceProject/android-audiobook/pull/58 (not a …

Update reading position on play, pause, and stop

---

README-CHANGES.xml
simplified-accounts-json/src/main/java/org/nypl/simplified/accounts/json/AccountProviderDescriptionCollectionParser.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/accounts/AccountProviderDescriptionCollectionParserTest.kt
simplified-ui-accounts/src/main/java/org/nypl/simplified/ui/accounts/AccountListRegistryViewModel.kt

This PR updates the source of the library logo loading by passing the catalog images list obtained from the catalog parsing instead of passing an empty list. Then, this PR removes theauthentication document fetching from the registry feed because it was retrieving a large document just to get a thumbnail image.
The logic of downloading the library logos was a bit heavy for the app and the backend since the app was fetching the authentication document of each library when adding a library, as explained in [this ticket](https://www.notion.so/lyrasis/Android-Load-library-logos-from-s3-links-in-registry-feed-4227877d179d4a1ca943b39b9dca9d3a). …

Updated library logos loading source in registry feed

---

README-CHANGES.xml
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogFeedViewModel.kt

This PR filters the loaned and available books with an expired loan end date.
There's a [feature request](https://www.notion.so/lyrasis/Android-Hide-titles-on-My-Books-while-offline-if-expiry-date-has-passed-7ea413f3a3d5413a9eeec24d60f70b4a) to hide the expired books from "My Books" in offline mode.
Get some books if you don't have any on "My Books"
Close the app, turn off your internet connection and change the device's date to 1 or 2 months later
Still offline, return to the app and go to "My Books"
Confirm some or even all titles are not there …

Hidden expired loans in offline mode

---

README-CHANGES.xml
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailFragment.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogBookDetailViewModel.kt
simplified-ui-catalog/src/main/java/org/nypl/simplified/ui/catalog/CatalogButtons.kt
simplified-ui-catalog/src/main/res/layout/book_detail.xml
simplified-ui-catalog/src/main/res/values/stringsCatalog.xml

This PR updates the position of the preview button so it can be side by side with the other button options. This PR also hides the preview button in case the user already has the full book. Finally, the PR also changes the label "Read Preview" to "Read Sample"
There's a [feature request](https://www.notion.so/Don-t-show-the-preview-button-after-the-user-gets-the-full-book-8b1caaf026c04e769361184f9f77415b) to update the preview button position, text and displaying logic to match the iOS version of the app.
Open the "Palace Marketplace Integration Library"
Open the book "Love, Penelope" by Joanne Rocklin
Confirm the "Read …

Changed position and text of preview button

---

README-CHANGES.xml
simplified-viewer-preview/src/main/assets/preview_player_commands.js
simplified-viewer-preview/src/main/java/org/nypl/simplified/viewer/preview/BookPreviewEmbeddedFragment.kt

This PR runs a Javascript code block when the earphones are unplugged while the audiobook preview is being played, so the WebView can get that action and pause the preview.
There's a [ticket with a bug](https://www.notion.so/lyrasis/Android-Audiobook-samples-keep-playing-after-headphones-are-removed-2f32122e07e24bea8024716a73954634) saying that for some audiobooks the preview is not stopped when the earphones are unplugged.
Select "OverDrive Integration Test Library"
Open any audiobook
Click on "Play Sample"
Confirm the layout and commands are similar to [this](https://user-images.githubusercontent.com/79104027/231117054-c9 …

Fixed WebView audiobook preview not pausing when earphones are unplugged

---

README-CHANGES.xml

Updated changeling to include Bluetooth audio controls change. Now Bluetooth media controls (e.g. on headphones) can be used to play, pause, and skip to previous or next track.
Bluetooth audio controls are useful for navigating via Bluetooth devices such as standalone media controllers or headphones.
Bluetooth headphones with a minimum of play, pause, next, and previous track (or standalone Bluetooth medial controls devices) should be used to test this.
No dependencies.
Yes.
No.
**Did …

Updated changelog

---

README-CHANGES.xml

Update changelog to include new change to android-audiobook to always show lock screen audio controls.
Better user experience. 
[android-audiobook PR here] (https://github.com/ThePalaceProject/android-audiobook/pull/65)
[Notion ticket here](https://www.notion.so/lyrasis/Lock-screen-controls-do-not-appear-on-Android-13-87fdfcebc86547e8896473bba0f4c02d)
Play an audiobook. Lock the device (turn off the screen). Turn the screen back on. Notice the audio playback controls are showing on the lock screen. Test that they work as expected. Swipe the playback controls to dismiss them. Unlock the phone. Now lock/unlock the device again (turn the screen …

Updated changelog: always show lock screen audio controls

---

README-CHANGES.xml
simplified-bookmarks/src/main/java/org/nypl/simplified/bookmarks/internal/BHTTPCalls.kt
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookHelpers.kt
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookPlayerActivity.kt

This PR fixes audiobook bookmarks being incorrectly displayed by hiding those who don't have a valid url. Also, this PR deletes some unnecessary code that could have been causing the bookmarks to be properly deleted.
There's [a ticket with a bug](https://ebce-lyrasis.atlassian.net/browse/PP-48) saying that some audiobook bookmarks are failing to be deleted and then they seem to be duplicated while being displayed to the user.
Open the app
Get an audiobook
Tap “Listen”
Add several bookmarks
Open TOC - Bookmarks
Delete all the bookmarks
Close the book
Tap “Listen” again
Open TOC - Bookmarks
Confirm the bookmarks …

Fixed audiobook bookmarks being incorrectly displayed and failing to be deleted

---

README-CHANGES.xml
simplified-lcp/src/main/java/org/nypl/simplified/lcp/LCPContentProtectionProvider.kt
simplified-lcp/src/main/res/values/strings.xml

This PR removes the hardcoded string for the LCP passphrase dialog message and sets it as the `hint` field inside the LCPLicense object
There's a [bug report](https://ebce-lyrasis.atlassian.net/browse/PP-13) saying the message is always the same for every library with LCP protected books and that it should be dynamically shown depending on the response we receive.
Go to debug options and activate "Enable manual LCP passphrase" option
Select a library with books with LCP protection
Open a book with LCP protection
Confirm the dialog opens and still displays a message …

Removed hardcoded message from LCP passphrase dialog

---

README-CHANGES.xml
simplified-bookmarks-api/src/main/java/org/nypl/simplified/bookmarks/api/BookmarkHTTPCallsType.kt
simplified-bookmarks-api/src/main/java/org/nypl/simplified/bookmarks/api/BookmarkServiceUsableType.kt
simplified-bookmarks/src/main/java/org/nypl/simplified/bookmarks/internal/BHTTPCalls.kt
simplified-bookmarks/src/main/java/org/nypl/simplified/bookmarks/internal/BService.kt
simplified-bookmarks/src/main/java/org/nypl/simplified/bookmarks/internal/BServiceOpCreateRemoteBookmark.kt
simplified-bookmarks/src/main/java/org/nypl/simplified/bookmarks/internal/BServiceOpDeleteBookmark.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/bookmarks/NullBookmarkService.kt
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookHelpers.kt
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookPlayerActivity.kt
simplified-viewer-audiobook/src/main/res/values/strings.xml
simplified-viewer-epub-readium2/src/main/java/org/nypl/simplified/viewer/epub/readium2/Reader2Activity.kt
simplified-viewer-epub-readium2/src/main/java/org/nypl/simplified/viewer/epub/readium2/Reader2Bookmarks.kt
simplified-viewer-epub-readium2/src/main/res/values/strings.xml

When adding a bookmark, an object of the type  Bookmark was created but it was given 'null' as the URI field value which was causing the bookmark to not be able to be deleted since it needs a non-null URI in order to perform the operation on the server. However, the UI was being updated as if it was actually deleted, so when the user left the audiobook/ebook and returned, they'd still be seeing the "deleted" bookmarks. This PR fixes this bug by receiving the created bookmark from the server and saving it with a valid URI so it can be properly deleted right after being added or later. This PR also updates the UI in order to give some feedback to the user when the bookmark is being created/deleted.
There's a [report …

Fixed bug of bookmarks not being deleted

---

README-CHANGES.xml
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/BorrowContextType.kt
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/BorrowTask.kt
simplified-books-borrowing/src/main/java/org/nypl/simplified/books/borrowing/internal/BorrowLCP.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/borrowing/BorrowTaskTest.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/mocking/MockBorrowContext.kt

This PR adds an empty passphrase as a default value to return when two conditions are met: no LCP passphrase on the feed entry and the LCP passphrase manual input setting is enabled.
There's a comment on [this ticket](https://ebce-lyrasis.atlassian.net/browse/PP-13) saying that there are some LCP protected books that are failing to be downloaded on the Android app while the same books are downloaded on the iOS version
Enable the hidden libraries option on the Debug options
Go to Libraries and select _Cerberus Test Library 1_
Open any book from _EDRLab LCP Test_ lane
Download it and confirm the download is successful even …

Added default LCP passphrase to be returned when the feed entry doesn't have one and the manual input is enabled

---

simplified-futures/src/main/java/org/nypl/simplified/futures/FluentFutureExtensions.kt
simplified-viewer-epub-readium2/build.gradle
simplified-viewer-epub-readium2/src/main/java/org/nypl/simplified/viewer/epub/readium2/Reader2Activity.kt
simplified-viewer-epub-readium2/src/main/java/org/nypl/simplified/viewer/epub/readium2/Reader2Bookmarks.kt

Affects: https://ebce-lyrasis.atlassian.net/browse/PP-185
This corrects a number of bookmarking issues.
* The existing code leaked a thread on every controller event by creating an executor each time but not shutting it down.
* The SR2 code has been updated to publish the correct event on each page turn.
* The code now unconditionally creates a local bookmark even if saving the remote bookmark failed.
* Toast messages are not shown for page turns because this tends to result in an endless queue of toast messages.
https://ebce-lyrasis.atlassian.net/browse/PP-187
Open an ePub and verify that turning pages and creating bookmarks works. Verify …

PP-187: Fix some bookmark issues

---

simplified-main/src/main/java/org/nypl/simplified/main/MainActivity.kt

This refactors the deep link intercept method to avoid several potential crashes.
Affects: https://ebce-lyrasis.atlassian.net/browse/PP-181
Try using a deep link after creating a library card.
None.
Nope.
Nope.
Unfortunately, I've not been able to get a link to actually trigger the app. This code change does make the original crash impossible, but somebody with a working device/link will need to try it.

PP-181: Refactor deep link method

---

README-CHANGES.xml
simplified-main/src/main/java/org/nypl/simplified/main/MainFragmentViewModel.kt

This PR adds a try-catch to the holds call on the MainFragmentViewModel because the app was crashing everytime the call was interrupted.
There's a [ticket reporting a bug](https://ebce-lyrasis.atlassian.net/browse/PP-116) that when an audiobook timer was set more than once in a short time the app was crashing. This was one of the reasons causing the call interruption and consequent crash, but there were more since this crash was reported several times on Crashlytics.
Select any library
Open any audiobook
Start playing it
Change the playback speed
Set a timer
Set a different time right after setting the first one
Confirm …

Fixed crash after setting an audiobook timer more than once in a short time

---

README-CHANGES.xml
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookHelpers.kt

This PR adds a try-catch to two calls to the server: deleting and saving a bookmark. This is done to prevent the call from reaching its defined timeout and crashing the app.
There are two tickets ([here](https://ebce-lyrasis.atlassian.net/browse/PP-218) and [here](https://ebce-lyrasis.atlassian.net/browse/PP-219)) reporting a crash that was happening after saving a bookmark to the server. Even though this [ticket's crash reproducing steps](https://ebce-lyrasis.atlassian.net/browse/PP-219) aren't related with the bookmarks the reason why it's crashing is because there's a timeout while saving the bookmark on the server (because it automatically saves the reading position) as it can be verified on …

Fixed crash when saving a bookmark on the server

---

simplified-app-palace/build.gradle

This PR updates the expected SHA-256 value for the secrets.conf file.
The pipeline is failing because it's expecting one value and it's given a different one.
The pipeline should successfully run
None
No
No

Updated secrets.conf expected SHA value

---

README-CHANGES.xml
simplified-books-time-tracking/src/main/java/org/nypl/simplified/books/time/tracking/TimeTrackingService.kt

This PR fixes a crash when the user hasn't enabled the time traking feature and leaves the audiobook player screen after listening to it for some time.
There's been a [Crashlytics stability issue](https://console.firebase.google.com/project/the-palace-project/crashlytics/app/android:org.thepalaceproject.palace/issues/4821ffda39f2376b4b9d1efd42a98bb0?time=last-seven-days&sessionEventKey=64D5E61703AD00011A2DDC0F82053334_1844413704638796368) related with this problem.
Go to Debug settings and disable the "Time tracking" option
Go to Minotaur Test Library
Open any audiobook from Biblioboard
Listen to it for some time
Close the …

Fixed crash when time tracking is not enabled

---

simplified-books-time-tracking/src/main/java/org/nypl/simplified/books/time/tracking/TimeTrackingService.kt
simplified-profiles-api/src/main/java/org/nypl/simplified/profiles/api/ProfilePreferences.kt
simplified-profiles/src/main/java/org/nypl/simplified/profiles/ProfileDescriptionJSON.kt
simplified-profiles/src/main/java/org/nypl/simplified/profiles/ProfilesDatabases.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/profiles/ProfileDescriptionJSONTest.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/mocking/MockProfile.kt
simplified-ui-settings/src/main/java/org/nypl/simplified/ui/settings/SettingsDebugFragment.kt
simplified-ui-settings/src/main/java/org/nypl/simplified/ui/settings/SettingsDebugViewModel.kt
simplified-ui-settings/src/main/res/layout/settings_debug.xml

~This sets the default for audio book time tracking to be on instead of off. Note that, for installations that have been used during development of the time tracking feature, there might already be a setting of "off" saved to the device, so this will require manually toggling the setting back on again. We have no way to know if the setting is "off" because the user turned it off, or if it's "off" because that was the default and the user never even saw the debug settings screen. This shouldn't affect anyone upgrading from a production release, or any new installs.~
This turns on time tracking unconditionally. Any preferences to turn it off have been removed, along with the settings in the debug menu.
Affects: …

PP-328: Audio book time tracking is on!

---

simplified-books-time-tracking/src/main/java/org/nypl/simplified/books/time/tracking/TimeTrackingService.kt

This avoids any use of the time tracking service if the current book doesn't have a time tracking URI.
Affect: https://ebce-lyrasis.atlassian.net/browse/PP-353
Try an audio book without a time tracking URI.
None.
No need.
No need.
@io7m tried it

PP-353: Correct a lateinit issue

---

README-CHANGES.xml
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookLoadingFragment.kt
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookPlayerActivity.kt
simplified-viewer-audiobook/src/main/java/org/nypl/simplified/viewer/audiobook/AudioBookViewer.kt

This PR adds a fix for a [recurring crash](https://console.firebase.google.com/project/the-palace-project/crashlytics/app/android:org.thepalaceproject.palace/issues/4ad2d33871ca99f04955282e20c54b32) when trying to open a an audiobook with a null manifest.
There's been a peak of crashes, as reported [here](https://ebce-lyrasis.atlassian.net/browse/PP-382) related to this issue.
I'm not sure in which book(s) this's been happening with, so I don't know exactly how to replicate this issue, but trying to open a significant number of audiobooks should not result in a crash.
None
**Have you …

Fixed crash when opening an audiobook with a null manifest

---

README-CHANGES.xml
simplified-viewer-audiobook/src/main/java/org/librarysimplified/viewer/audiobook/AudioBookPlayerActivity.kt

This changes the audio book player activity to initialize services eagerly so that they're available to the error handling methods should the activity be called without usable parameters.
Affects: https://ebce-lyrasis.atlassian.net/browse/PP-406
Unfortunately, we don't know why the audio book player activity was being called without usable parameters, because we don't yet know why some manifests are resulting in unexpected null values.
None.
Yes.
N/A
**Did someone actually run this …

PP-406: Initialize services eagerly

---

simplified-opds-core/src/main/java/org/nypl/simplified/opds/core/OPDSAcquisitionFeedEntryParser.java
simplified-tests/src/test/java/org/nypl/simplified/tests/opds/OPDSFeedEntryParserTest.java
simplified-tests/src/test/resources/org/nypl/simplified/tests/opds/bug-pp-465.xml

This allows the OPDS parser to handle empty author elements.
Affects: https://ebce-lyrasis.atlassian.net/browse/PP-465
Check the Minotaur front page.
None.
N/A
N/A
@io7m Ran the new test, and checked Minotaur.

PP-465: Make the OPDS entry parser tolerant to missing author names

---

README-CHANGES.xml
simplified-ui-accounts/src/main/res/layout/auth_saml.xml
simplified-ui-accounts/src/main/res/values/strings.xml

This adds a missing accessibility label to the SAML login button.
Affects: https://ebce-lyrasis.atlassian.net/browse/PP-418
Try selecting the button with Talkback enabled and verify that there's a usable button description.
None.
Yes.
N/A
@io7m Tried the button with Samsung Talkback enabled. I assume Google Talkback would work similarly!

PP-418: Fix SAML login button accessibility label

---

README-CHANGES.xml
simplified-ui-catalog/src/main/res/layout/book_detail.xml
simplified-ui-catalog/src/main/res/layout/feed_lane_item.xml
simplified-ui-catalog/src/main/res/values/dimensions.xml

This sets maximum widths for covers so that very large covers can no longer break the UI.
Before:
After:
https://ebce-lyrasis.atlassian.net/browse/PP-443
Try Minotaur. The book is on the front page now.
None.
Yes.
N/A
@io7m Took the screenshots above!

PP-443: Restrict cover widths

---

simplified-ui-settings/src/main/res/layout/settings_debug.xml
simplified-ui-settings/src/main/res/values/strings.xml

This adds a new string at the bottom of the debug menu that should be displayed in Spanish if the device is set to Spanish and Transifex is actually working.
Helps with testing PP-86.
https://ebce-lyrasis.atlassian.net/browse/PP-86
Set your device to Spanish and see if the string at the bottom of the debug screen is Spanish.
None.
N/A
N/A
@io7m Ran the app but only in English.

PP-86: Add a string that should be translated by Transifex.

---

README-CHANGES.xml
simplified-ui-accounts/src/main/java/org/nypl/simplified/ui/accounts/AccountDetailFragment.kt

The current code was failing to set usernames/passwords for token auth,
and also failing to reconfigure the UI in the `onStart()` method. This
would cause inconsistent visuals when resuming the app after having
locked the screen.
https://ebce-lyrasis.atlassian.net/browse/PP-307
Try locking the device when on the account details screen, and then unlocking it. See the video in PP-307 for an example of what _shouldn't_ happen. :slightly_smiling_face: 
None.
Yes.
N/A
**Did someone …

PP-307: Resume account views correctly

---

README-CHANGES.xml
simplified-bookmarks/src/main/java/org/nypl/simplified/bookmarks/internal/BServiceOpCreateBookmark.kt

This PR changes the way the bookmarks are created in order to fix the bug of not being able to be deleted. By creating the local bookmark first, the displayed bookmark item had a `null` bookmark which was causing it to fail to be deleted. So, if the user pressed the "add bookmark" button and immediately entered the bookmarks page before the message "bookmark created" was displayed, the bookmark would fail to be deleted.
There's a [bug report](https://ebce-lyrasis.atlassian.net/browse/PP-450) saying the bookmarks are not being deleted sometimes.
Open any Epub
Add a bookmark and open the TOC page and go to the bookmarks tab …

Fixed bookmarks not being deleted

---

README-CHANGES.xml
simplified-feeds-api/src/main/java/org/nypl/simplified/feeds/api/FeedFacets.kt
simplified-opds-core/src/main/java/org/nypl/simplified/opds/core/OPDSFeedParser.java
simplified-tests/src/test/resources/org/nypl/simplified/tests/opds/acquisition-facets-1.xml

This PR updates the OPDS facet parsing logic by ignoring the content of the facetGroupType.
There's a [ticket with a bug](https://ebce-lyrasis.atlassian.net/browse/PP-476) saying the catalog is no longer displaying the tabs. The iOS app is still displaying them because they ignore the content of the attribute `facetGroupType` as long as the key is there.
Confirm there are tabs in the top of the catalog
None
Yes
No
**Did someone actually run this code to verify it …

Updated OPDS facet parsing by ignoring the content of facetGroupType

---

README-CHANGES.xml
simplified-opds-core/src/main/java/org/nypl/simplified/opds/core/OPDSFeedParser.java
simplified-tests/src/test/resources/org/nypl/simplified/tests/opds/acquisition-facets-1.xml

This PR reverts the logic added in [this PR](https://github.com/ThePalaceProject/android-core/pull/232)
The server should adapt the feed response in order to specify all the attributes' namespace, as explained [here](https://ebce-lyrasis.atlassian.net/browse/PP-476?focusedCommentId=11683)
In the catalog, the tabs should've disappeared
None
Yes, by removing the previous entry
No

Reverted OPDS Feed parsing

---

README-CHANGES.xml
simplified-app-palace/build.gradle.kts
simplified-books-time-tracking/build.gradle.kts
simplified-books-time-tracking/src/main/java/org/nypl/simplified/books/time/tracking/TimeTrackingService.kt
simplified-tests/build.gradle.kts

This PR adds missing dependencies related to the ULID generator library which was causing the audiobook UI to freeze when trying to create the first time entry.
There's a [bug report](https://ebce-lyrasis.atlassian.net/browse/PP-541) saying that the audiobook UI is freezing after pressing the "Play" button.
Add Lyrasis Reads
Open a Biblioboard audiobook
Tap "Play" button
Confirm everything is working just fine
None
Yes
No
**Did someone actually run this code to …

Fixed Audiobook UI freezing after pressing 'play'

---

README-CHANGES.xml
simplified-app-palace/build.gradle.kts

This PR fixes a recurring crash when trying to create a virtual library card
There's a [bug report](https://ebce-lyrasis.atlassian.net/browse/PP-583) saying there's been a huge number of crashes when creating a library card.
Select a library that allows Virtual Library Card creation (p.e., Bethel Public Library)
Click on "Create Card"
Confirm the app is not crashing
None
Yes
No

Fixed crash when creating a library card

---

README-CHANGES.xml
simplified-ui-catalog/src/main/java/org/librarysimplified/ui/catalog/CatalogFeedFragment.kt
simplified-ui-catalog/src/main/java/org/librarysimplified/ui/catalog/CatalogFeedViewModel.kt

This PR changes how the feed handles a new facet/tab click. Instead of creating and adding a new fragment for the feed, it just updates the UI and reloads the feed with some new arguments.
There's a [feature request](https://ebce-lyrasis.atlassian.net/browse/PP-577) to make this similar as it is on the iOS app
Select "LYRASIS Reads"
On the Catalog tab, press "eBooks"
Confirm the title remains as "Catalog" and there's the Palace logo instead of a back arrow
Press "AudioBooks"
Confirm the title remains as "Catalog" and there's the Palace logo instead of a back arrow
None …

Adjusted feed tabs navigation to keep the "Catalog" on the screen

---

README-CHANGES.xml
simplified-books-controller/src/main/java/org/nypl/simplified/books/controller/ProfileAccountLoginTask.kt
simplified-books-controller/src/main/java/org/nypl/simplified/books/controller/ProfileAccountLogoutTask.kt
simplified-main/src/main/java/org/librarysimplified/main/MainActivity.kt
simplified-notifications/src/main/java/NotificationTokenHTTPCalls.kt
simplified-notifications/src/main/java/NotificationTokenHTTPCallsType.kt
simplified-profiles-api/src/main/java/org/nypl/simplified/profiles/api/ProfilePreferences.kt
simplified-profiles/src/main/java/org/nypl/simplified/profiles/ProfileDescriptionJSON.kt
simplified-profiles/src/main/java/org/nypl/simplified/profiles/ProfilesDatabases.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/profiles/ProfileAccountLoginTaskContract.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/profiles/ProfileAccountLogoutTaskContract.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/books/profiles/ProfileDescriptionJSONTest.kt
simplified-tests/src/test/java/org/nypl/simplified/tests/mocking/MockProfile.kt
simplified-ui-settings/src/main/java/org/nypl/simplified/ui/settings/SettingsDebugFragment.kt
simplified-ui-settings/src/main/java/org/nypl/simplified/ui/settings/SettingsDebugViewModel.kt
simplified-ui-settings/src/main/res/layout/settings_debug.xml
simplified-ui-settings/src/main/res/values/strings.xml

This PR enables the push notifications by default and removes the option from the debug settings.
There's a [feature request](https://ebce-lyrasis.atlassian.net/browse/PP-571) to enable the push notifications by default now that they're tested
Open the Palace app in two different devices
Log in two different accounts but in the same library
With one account borrow a book that only has on copy
With the other account, reserve the same book
Again with the first account, return the book
Confirm a push notification is received in the second account
None
Yes …

Enabled push notifications by default

---

README-CHANGES.xml
simplified-viewer-epub-readium2/src/main/java/org/librarysimplified/viewer/epub/readium2/Reader2Activity.kt

This PR fixes a recurring crash on the ReaderFragment when more than one fragment tries to listen to a ViewModel observable that can only be subscribed once.
There's a [bug report](https://ebce-lyrasis.atlassian.net/browse/PP-633) mentioning there's been a significant number of crashes because of this
First you need to enable the Developer Options of your mobile phone (please Google how to do it as it's different from device to device)
Open the Developer Options
Enable the option "Don't keep activities"
Open any Ebook
Minimize the app
Reopen the app
Confirm the app didn't crash …

Fixed crash on Reader screen due to more than one Fragment instance

---

README-CHANGES.xml
simplified-app-palace/build.gradle.kts
simplified-app-palace/src/main/AndroidManifest.xml
simplified-app-palace/src/main/res/values-v31/themes.xml
simplified-app-palace/src/main/res/values/themes.xml
simplified-main/build.gradle.kts
simplified-tests/build.gradle.kts
simplified-ui-accounts/build.gradle.kts
simplified-ui-catalog/build.gradle.kts
simplified-ui-errorpage/build.gradle.kts
simplified-ui-navigation-tabs/build.gradle.kts
simplified-ui-onboarding/build.gradle.kts
simplified-ui-settings/build.gradle.kts
simplified-ui-splash/build.gradle.kts
simplified-viewer-audiobook/build.gradle.kts
simplified-viewer-epub-readium2/build.gradle.kts
simplified-viewer-pdf-pdfjs/build.gradle.kts
simplified-viewer-preview/build.gradle.kts

This PR updates the app's default theme in order to remove the default SplashScreen added in all the Android 12+ devices.
There's a [bug report](https://ebce-lyrasis.atlassian.net/browse/PP-585) saying that in some devices there are two splash screens being shown: the device's default and the app's splash screen.
Open the Palace app on an Android 12+ device
Confirm there's just the app's splash screen
Open the Palace app on an Android 11- device
Confirm there's just the app's splash screen
[This PR](https://github.com/ThePalaceProject/android-theme/pull/11) needs to be merged first
**Have …

Removed the Android 12+ devices default splash screen

---

README-CHANGES.xml
simplified-ui-catalog/src/main/java/org/librarysimplified/ui/catalog/CatalogBookDetailFragment.kt

This adjusts the code so that the "Read Sample" button is no longer present for books that are already loaned.
https://ebce-lyrasis.atlassian.net/browse/PP-642
Most of the Palace Marketplace books on Minotaur have samples. Check that you don't see a Read Sample button in the book detail page when you've borrowed a book.
None.
Yes.
N/A
@io7m Tried it on the Palace Marketplace.

PP-642: No previews for loans

---

simplified-app-palace/build.gradle.kts
simplified-books-time-tracking/build.gradle.kts
simplified-books-time-tracking/src/main/java/org/nypl/simplified/books/time/tracking/TimeTrackingService.kt
simplified-tests/build.gradle.kts

This is a partial fix for PP-693. We were using a ULID library that can't work on old devices due to them missing the standard `java.time` package.
Affects: https://ebce-lyrasis.atlassian.net/browse/PP-693
Unfortunately, the player still appears to be broken (and I'm debugging right now). This at least makes it slightly less broken.
None.
Not until the problem is actually fixed.
N/A
@io7m Verified one of the problems went …

PP-693 (partial): Switch to a new ULID library

---

simplified-bookmarks/src/main/java/org/nypl/simplified/bookmarks/internal/BServiceOpSyncOneAccount.kt
simplified-ui-images/src/main/java/org/nypl/simplified/ui/images/ImageAccountIcons.kt

This makes a couple of changes to assist with (but not solve PP-663):
* We no longer log account list icons, because some of them are still giant base64 encoded PNGs that end up in logs.
* We accept the fact that book database entries can disappear when syncing bookmarks
Affects: https://ebce-lyrasis.atlassian.net/browse/PP-663
Nothing, really. There's just less noise in the logs now.
None.
N/A
N/A
@io7m Enjoyed the peace and …

PP-663 (Partial): Reduce logging volume

---

README-CHANGES.xml
simplified-ui-navigation-tabs/src/main/java/org/librarysimplified/ui/navigation/tabs/TabbedNavigator.kt

Don't attempt to pop the stack unless there's something to pop. 
Catch any NullPointerExceptions that the library might raise.
Affects: https://ebce-lyrasis.atlassian.net/browse/PP-714
Nothing new. Just see if the crashes stop after `1.8.0`...
None.
Yes.
N/A
@io7m Used the catalog for a while. I've not seen the original crash, so I just wanted to check that I didn't break the catalog.

PP-714: Make BottomNavigator bug non-fatal

---

README-CHANGES.xml
simplified-app-palace/build.gradle.kts
simplified-tests/build.gradle.kts
simplified-viewer-pdf-pdfjs/build.gradle.kts
simplified-viewer-pdf-pdfjs/src/main/java/org/librarysimplified/viewer/pdf/pdfjs/PdfServer.kt
simplified-viewer-pdf-pdfjs/src/main/java/org/librarysimplified/viewer/pdf/pdfjs/factory/PdfDocumentFactory.kt
simplified-viewer-pdf-pdfjs/src/main/java/org/librarysimplified/viewer/pdf/pdfjs/factory/PdfReaderDocument.kt

This PR updates the app to support the latest version of Readium
There's a [feature request](https://ebce-lyrasis.atlassian.net/browse/PP-704) to update the Readium version
Open any Ebook
Confirm everything is working
Return and open any PDF
Confirm everything is working
[This PR](https://github.com/ThePalaceProject/android-r2/pull/55) also needs to be merged
Yes
No

Updated Readium version

---

simplified-mdc/src/main/java/org/librarysimplified/mdc/MDCKeys.kt
simplified-viewer-api/src/main/java/org/nypl/simplified/viewer/api/Viewers.kt
simplified-viewer-audiobook/src/main/java/org/librarysimplified/viewer/audiobook/AudioBookPlayerActivity.kt
simplified-viewer-epub-readium2/src/main/java/org/librarysimplified/viewer/epub/readium2/Reader2Activity.kt
simplified-viewer-pdf-pdfjs/src/main/java/org/librarysimplified/viewer/pdf/pdfjs/PdfReaderActivity.kt
simplified-viewer-preview/src/main/java/org/librarysimplified/viewer/preview/BookPreviewActivity.kt

We weren't logging OPDS feed entry IDs. Those are the most useful values when debugging problems with specific books.
We ran into this earlier when trying to debug a Picasso crash.
Check that the new fields appear in Crashlytics when there's a crash...
None.
N/A
N/A
@io7m Tried it.

Add some missing MDC logs

---

README-CHANGES.xml
simplified-ui-accounts/src/main/res/drawable-night/ic_delete.xml
simplified-ui-accounts/src/main/res/drawable/ic_delete.xml
simplified-ui-accounts/src/main/res/layout/account_list_item_old.xml

It seems that no icon was assigned at all to the accounts list deletion button. Now there is!
Fix: https://ebce-lyrasis.atlassian.net/browse/PP-738
None.
Yes.
N/A
@io7m Took the above screenshot.

PP-738: Make account deletion icon visible

---

README-CHANGES.xml
simplified-accounts-database/src/main/java/org/nypl/simplified/accounts/database/AccountsDatabase.kt
simplified-books-controller/src/main/java/org/nypl/simplified/books/controller/ProfileAccountDeleteTask.kt
simplified-ui-accounts/src/main/java/org/nypl/simplified/ui/accounts/AccountListAdapter.kt
simplified-ui-accounts/src/main/res/values/strings.xml

* Remove the account deletion popup menu in favour of a plain dialog popup.
* Fix the missing error message when trying to delete the last account.
* Use "Remove" instead of "Delete" for consistency.
Fix: https://ebce-lyrasis.atlassian.net/browse/PP-756
These are covered by A1QA, apparently!
None.
Yes.
N/A
@io7m Tried it.

PP-756, PP-757: Adjust account deletion UI
